facilitator/Cargo.lock, facilitator/Cargo.toml
Bad news: the build broke because we changed the default branch of
libprio-rs to main, and eventually deleted the master branch, so the
dependency became unresolvable.
Good news: our CI setup works!
=> facilitator: update libprio dependency branch

facilitator/src/intake.rs, facilitator/src/sample.rs
This small patch removes some calls to `clone` for types that are either pointers or implement `Copy`.
=> Remove Some Clones

facilitator/Cargo.lock, facilitator/Cargo.toml, facilitator/src/batch.rs, facilitator/src/bin/facilitator.rs, facilitator/src/lib.rs, facilitator/src/sample.rs, facilitator/src/transport.rs
Adds a Transport implementation which reads objects from and writes
objects to S3. The various subcommands on the facilitator tool can now
take arguments like `s3://bucket-name` as well as local paths for input
and output storage.
Addresses #19
=> facilitator: Add S3Transport

facilitator/Cargo.lock, facilitator/Cargo.toml
We need to turn this feature on so that we can decompress Avro messages
that were compressed using the snappy codec. Happily this requires no
code changes; avro_rs automatically detects if it receives snappy
messages and decompresses appropriately.
=> facilitator: enable snappy feature on avro_rs

facilitator/Cargo.lock, facilitator/Cargo.toml, facilitator/src/bin/facilitator.rs, facilitator/src/transport.rs, terraform/main.tf, terraform/modules/facilitator/facilitator.tf, terraform/modules/gke/gke.tf, terraform/modules/kubernetes/kubernetes.tf, terraform/variables/demo-gcp.tfvars
This commit teaches facilitator to make authenticated calls to Amazon S3
using a GCP service account wired into Kubernetes pods using GKE
Workload Identity. The Terraform module also now creates ingestion,
validation and sum part buckets for each facilitator instance in a
cluster, with appropriate policies and IAM roles to permit our
facilitator/data share processors in GCP to write objects to them.
=> OIDC auth for accessing S3 buckets

README.md, deploy-tool/.gitignore, deploy-tool/main.go, facilitator/Cargo.lock, facilitator/Cargo.toml, facilitator/src/bin/facilitator.rs, facilitator/src/lib.rs, facilitator/src/manifest.rs, facilitator/src/test_utils.rs, terraform/Makefile, terraform/README.md, terraform/main.tf, terraform/modules/data_share_processor/data_share_processor.tf, terraform/modules/gke/gke.tf, terraform/modules/kubernetes/kubernetes.tf, terraform/modules/manifest/manifest.tf, terraform/variables/demo-gcp.tfvars
This PR contains a series of commits that enables us to deploy data share processors in support of arbitrarily many ingestor servers and PHAs. The specific features are discussed in each commit message. There are several missing pieces here (tests on deploy-tool, support in deploy-tool for certifying packet decryption keys, Terraform management of manifest domain and its DNS, inclusion of key-identifier in batch signatures, hooking up peer manifest discovery to arguments on facilitator) but I wanted to get all these changes visible to our team because they might inform how the workflow manager will be built, and also so that the remaining tasks could be tackled in parallel.
Partially addresses: #20 #15
=>  Terraform: Kubernetes secrets, renames, manifests, construction of all necessary data share processors, deploy tooling

terraform/main.tf, terraform/modules/data_share_processor/data_share_processor.tf, terraform/modules/kubernetes/kubernetes.tf, terraform/modules/manifest/manifest.tf
As of just recently, MITRE/the portal server has assumed responsibility
for ownership of the buckets to which data share processors shall write
sum part batches. To enable them to grant write permissions to our
servers, we create a GCP service account, and advertise it from our
global manifest. We then allow all the service accounts we create for
individual data share processor instances to impersonate that account.
=> terraform: create sum part writer service account

avro-schema/batch-signature.avsc, facilitator/src/aggregation.rs, facilitator/src/batch.rs, facilitator/src/bin/facilitator.rs, facilitator/src/idl.rs, facilitator/src/intake.rs, facilitator/src/lib.rs, facilitator/src/manifest.rs, facilitator/src/sample.rs, facilitator/src/test_utils.rs, facilitator/tests/integration_tests.rs
When evaluating a batch, a data share processor needs the identifier of the key it was signed with so it can look up the right public key in the peer's manifest. These commits reintroduce that Avro structure and teaches facilitator to use it when reading and writing batches.
Addresses #25
=> Reintroduce signature message and adopt it

terraform/main.tf, terraform/modules/manifest/manifest.tf, terraform/variables/demo-gcp.tfvars
Up until now, we had been using jrenken's donated domain portcull.is to
serve manifests. Amir bought us isrg-prio.org the other day, so we can
use the <env>.manifests.isrg-prio.org namespace now. Additionally, we
can now use a GCP managed DNS zone for manifests.isrg-prio.org. and
use Terraform to create A records in there for specific envs.
=> terraform: Google Cloud DNS for manifest domain

avro-schema/ingestion-data-share-packet.avsc, facilitator/src/batch.rs, facilitator/src/idl.rs, facilitator/src/sample.rs
Ingestion servers will not all be populating the encryption_key_id field
in PrioDataSharePacket, so we need to make that an optional field in the
Avro message.
Addresses #73
=> protocol: make encryption_key_id optional

terraform/Makefile
Since the Makefile currently proceeds on errors,
the deploy-tool invocation can obscure errors during make apply.
=> Remove deploy-tool invocation from Makefile.

terraform/Makefile, terraform/main.tf, terraform/modules/manifest/manifest.tf
This commit resolves some bugs around spinning up an env spanning
multiple GCP projects, or outside of one's gcloud default auth
credentials.
The `gsutil` invocations in the Makefile now get a -p (project)
parameter from the .tfvars file to ensure that Terraform backend buckets
are created in the correct project.
The google_dns_record_set resource in manifest.tf is now created in the
same project as the google_dns_managed_zone.
=> terraform: multi-project bug fixes

terraform/Makefile
Previously, `make prep` would get run on any change. That involved
expensive operations like installing providers.
This makes all the targets depend on `.terraform/terraform.tfstate`,
which is generated by make prep. Cuts time for `make apply`
approximately in half.
=> Speed up Makefile

facilitator/Cargo.lock, facilitator/Cargo.toml, facilitator/src/aggregation.rs, facilitator/src/batch.rs, facilitator/src/bin/facilitator.rs, facilitator/src/config.rs, facilitator/src/manifest.rs, facilitator/src/sample.rs, facilitator/src/transport.rs, facilitator/src/transport/gcs.rs, facilitator/src/transport/local.rs, facilitator/src/transport/s3.rs, facilitator/tests/integration_tests.rs, terraform/main.tf, terraform/modules/data_share_processor/data_share_processor.tf, terraform/modules/kubernetes/kubernetes.tf
Adds an implementation of the Transport trait which implements
authenticated reads and writes from Google Cloud Storage buckets. It
supports two auth scenarios:
- Using the default Oauth token retrieved from the GKE metadata service
- Obtaining an Oauth token to impersonate another service account
specified in GCSTransport::new.
The former case will allow ISRG's GCP workload deployment to read and
write from its own GCS buckets. The latter will allow us to write to the
MITRE Corporation's sum part buckets.
This also refactors some argument handling at the facilitator.rs level to
make it possible to specify on a per-transport basis how to do S3
authentication (for "s3://" style transports) or whether to impersonate
a GCP service account (for "gs://" style transports). This would allow
us …
=> facilitator: Add GCSTransport

facilitator/Dockerfile
Previously, the Docker build was not caching anything, meaning we would download and build all dependencies each time we build the container. This uses some tricks from https://shaneutt.com/blog/rust-fast-small-docker-image-builds/ to break the build process across cacheable Docker layers so rebuilds are much faster. I also switched to stripped debug builds, which are faster than release builds and suitable for our current use cases. Later on we should make debug / release an env variable, so the automatic publish in GH Actions can take its time and do a release build. And I moved from shipping Alpine to a bare binary in the container.
Size went from
580MB (full OS) to
18MB (release binary only) to
26 MB (debug binary only, stripped)
Time went from
4m52 (release, full build) to
2m22 …
=> Speed up Docker build for facilitator

terraform/modules/data_share_processor/data_share_processor.tf, terraform/modules/kubernetes/kubernetes.tf, workflow-manager/go.mod, workflow-manager/go.sum, workflow-manager/main.go
Add the necessary terraform to grant permission on ingestion buckets.
Add a flag to control which service is in use (GCS vs S3).
Pull a token from the GKE metadata endpoint and use it to authenticate to the S3 API.
=> Add S3 input bucket support to workflow-manager

facilitator/src/aggregation.rs, facilitator/src/batch.rs, facilitator/src/bin/facilitator.rs, facilitator/src/intake.rs, facilitator/src/manifest.rs, facilitator/src/transport.rs, facilitator/tests/integration_tests.rs
These commits teach the facilitator to handle multiple peer batch signing keys when evaluating trust over batches, and also to fetch JSON manifests from peers if adequate command line arguments are provided.
=> facilitator: discover parameters in peer manifests

facilitator/src/bin/facilitator.rs
Fix several places where we were looking for arguments in the top level
`matches` instead of the subcommand's `sub_matches`.
=> facilitator: fix argument parsing bugs

facilitator/src/batch.rs, facilitator/src/bin/facilitator.rs, facilitator/src/intake.rs, facilitator/src/lib.rs, facilitator/tests/integration_tests.rs, terraform/main.tf, terraform/modules/data_share_processor/data_share_processor.tf
This PR amends the Terraform to create an additional GCS bucket into which we shall write a copy of validation batches, to ensure we have our own validations available at aggregation time. It also extends the intake map step implementation in facilitator so that it can take two `SignableTransports`, which required teaching `BatchWriter` and `SidecarWriter` to deal with many potential writers under the covers.
=> Store copy of validation batches in internal bucket

terraform/main.tf, terraform/modules/data_share_processor/data_share_processor.tf, terraform/modules/kubernetes/kubernetes.tf, terraform/modules/manifest/manifest.tf, terraform/variables/demo-gcp.tfvars, workflow-manager/main.go
Common args are stored in a ConfigMap, which is used by workflow-manager.
Remove the secret keys from the workflow container, and have the workflow container configure the facilitator container to receive them. This introduces two new flags to the workflow container to pass the names of those secrets.
=> Add passthrough of args to workflow manager.

deploy-tool/main.go, facilitator/src/bin/facilitator.rs, facilitator/src/manifest.rs, terraform/main.tf, terraform/modules/kubernetes/kubernetes.tf, workflow-manager/main.go
deploy-tool:
libprio-rs expects to receive packet decryption keys as the X9.62
uncompressed public key, concatenated with the secret scalar, and not
the PKCS#8 documents that we were plugging into Kubernetes secrets.
deploy-tool now has logic to serialize the ECDSA keys it generates into
the desired format.
facilitator:
- generate-ingestion-sample now consults environment variables for the
ECIES encryption keys to use when generating data.
- argument handling was incorrectly looking for "batch-intake" instead
of "intake-batch"
- manifest::fetch_manifest now makes sure to construct https:// URLs
when fetching manifests.
terraform:
- Use the same key name within all Kubernetes secrets for simplicity
- Fix parameters to sample_maker cronjob
workflow-manager:
- parse aggregation ID from batch …
=> Various fixes to get intake-batch going

facilitator/src/bin/facilitator.rs, terraform/modules/kubernetes/kubernetes.tf, workflow-manager/main.go
- have facilitator check "INSTANCE_NAME" environment variable
- include cloud storage service schema in bucket URLs when constructing
intake config map
- have workflow-manager spawn jobs as appropriate service account
With this commit, plus some hacks not worth documenting, I was able to
get batch intake working, emitting validation batches to both a
simulated peer bucket in S3 and an internal bucket in GCS.
=> More fixes to get batch intake working

facilitator/Cargo.lock, facilitator/Cargo.toml, facilitator/src/bin/facilitator.rs, facilitator/src/transport/gcs.rs, facilitator/src/transport/s3.rs, terraform/modules/kubernetes/kubernetes.tf
The full log output including TRACE was way too noisy. This configures
our default log level as "info," which we can change with env vars
later. We can also specialize per-module, turning up logs from some
components without turning them on for everything.
=> Switch to env_logger for facilitator.

terraform/modules/kubernetes/kubernetes.tf, workflow-manager/main.go
This now takes `--ingestor-input` and `--ingestor-identity`. Also, parse the AWS account ID from the role ARN (passed as `--ingestor-identity`) rather than as a separate variable.
=> workflow-manager: update flags to match facilitator

deploy-tool/main.go, facilitator/src/bin/facilitator.rs, terraform/main.tf, terraform/modules/data_share_processor/data_share_processor.tf, terraform/modules/kubernetes/kubernetes.tf, terraform/variables/demo-gcp-peer.tfvars, terraform/variables/demo-gcp.tfvars
This series of commits creates a new env, `demo-gcp-peer`, and sets it and `demo-gcp` up to consume ingestion batches and then exchange validation batches. `demo-gcp` contains per-data-share-processor instances of a `sample-maker` job which is set up to emit ingestion batches to the data share processor in its own env as well as the corresponding one in `demo-gcp-peer`. We use the top-level variables `test_peer_environment` and `test_peer_environment_with_fake_ingestors` so that the envs can figure out if (1) they are being created in a test environment and (2) whether they are the test env that contains the sample-makers.
This also exposes a config value for whether this env's data share processors are "first", a.k.a. "PHA servers.
With these changes, I was able to encrypt and sign …
=> Set up two envs that can exchange validation shares

terraform/modules/kubernetes/kubernetes.tf, workflow-manager/main.go
This allows setting the facilitator image in Terraform rather than hardcoding it in the workflow-manager binary. Note that this allows anyone who can provide arguments to workflow-manager to cause workflow-manager to run an arbitrary image with access to the facilitator's secrets and service account.
=> Parameterize the facilitator image.

terraform/Makefile
Now that we have two envs we might be working on at once, destroying the local .terraform directory on each run seems like a good idea again.
This reverts commit a6a677743bb66ca67b127789a8cd7f8d01b6499a.
=> Revert "Speed up Makefile"

facilitator/src/bin/facilitator.rs, terraform/Makefile, terraform/README.md, terraform/main.tf, terraform/modules/data_share_processor/data_share_processor.tf, terraform/modules/fake_server_resources/fake_server_resources.tf, terraform/modules/kubernetes/kubernetes.tf, terraform/variables/demo-gcp-peer.tfvars, terraform/variables/demo-gcp.tfvars
This PR makes it easier to set up paired test environments via Terraform, with fake ingestion servers and also buckets into which sum parts can be written. It also removes ALL default values from facilitator (except that generate-ingestion-sample will still generate batch UUIDs and use the current date when constructing object keys), to make misconfigurations more obvious.
=> More robust paired test env

README.md
Extends the main README with some tips on how to use `gcloud` and `aws`
to simulate authentication flows that we use in the facilitator and
workflow-manager, as a debugging aid.
=> README: add guide to service account and roles

facilitator/src/bin/facilitator.rs, workflow-manager/main.go
This defines a new type `bucket`, which abstracts over the S3 vs
GS backend, and offers a `listFiles` method. It also provides new
methods to filter batches by readiness, introduces a notion of `infix`
to cover the `.batch.avro` / `.validity_0.avro` / `.validity_1.avro`
distinctions, and moves the bool fields used to calculate readiness
into `batchPath`. Also, batches are passed around as `batchPath`
objects now rather than strings.
=> workflow-manager: separate bucket reading from batch filtering

deploy-tool/main.go, terraform/modules/manifest/manifest.tf
It looks like the load balancer observes the cache-control header on the
origin, and Google Storage sets cache-control on a per-object basis,
with a default of 1 hour for public objects.
This prevents getting confusing results during debugging if you've edited
a manifest.
=> Apply Cache-Control: no-cache header on manifests

facilitator/src/manifest.rs, terraform/modules/kubernetes/kubernetes.tf
Add a more detailed error for PEM parse problems.
Set RUST_LOG=1 for sample-maker, and set RUST_BACKTRACE=1 for all Rust
jobs.
=> Improve debuggability.

.github/workflows/push-docker-image.yml
It looks like the tag created by the built-in docker build step isn't
visible to subsequent steps. I saw this when tagging a release:
docker tag letsencrypt/prio-facilitator:0.3.0 letsencrypt/prio-facilitator:latest
shell: /bin/bash -e {0}
Error response from daemon: No such image: letsencrypt/prio-facilitator:0.3.0
Error: Process completed with exit code 1.
This reverts to just running the docker build command as a step and then
consuming the tag.
=> Fix facilitator image push.

workflow-manager/main.go
Usually when one of those jobs fails, it will fail repeatedly. This prevents us from clogging up the podspace with dead jobs. We will eventually implement retry at a higher level in the workflow-manager.
=> workflow-manager: set a backoffLimit of 1 for spawned jobs

terraform/modules/kubernetes/kubernetes.tf, workflow-manager/main.go
Also:
- sort batches before working on them so output is more consistent
and easier to read.
- use withinInterval to filter out too-old batches, rather than
logging a line for each one.
- shorten the String() implementation for batchPath.
- remove some dead types.
=> workflow-manager: add cursoring to S3 API.

terraform/variables/gamlin-test.tfvars
Adds a tfvars file for the gamlin-test deploy ISRG will be using for the
infamous Narnia test.
At the moment, we only have one ingestor listed. We will add Google's
once their global manifest is ready. We also use well-formed but bogus
peer data share processor and portal server global manifests. Those
values will be updated as NCI and MITRE bring their Narnia
infrastructure online.
=> terraform: add gamlin-test tfvars

.github/workflows/ci-build.yml
We are going to branch for the Narnia test, creating a `release/narnia`
branch. This commit enables CI tests for that branch as well as pull
requests that target that branch.
The `release/**` matches arbitrary branches under `release`: https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#filter-pattern-cheat-sheet
=> GH actions: turn on CI for release branches

facilitator/src/aggregation.rs, facilitator/src/batch.rs, facilitator/src/bin/facilitator.rs, facilitator/tests/integration_tests.rs
Because there is only a single MITRE sum part bucket for each of ISRG
and NCI, we need to prefix the object keys where we write sum parts so
that (1) sums don't collide with each other and (2) MITRE can figure out
which locality a sum was for.
=> facilitator: use instance name in sum part objects

facilitator/README.md, facilitator/src/bin/facilitator.rs, facilitator/src/config.rs, facilitator/src/manifest.rs
Adds a `lint-manifest` subcommand to facilitator that can parse and
validate all kinds of manifests from either local files or fetches over
HTTPS.
I was going to write a pretty-printer and validator for Avro messages, too, but then I learned that Avro already publishes a Java jar that can do that (https://www.michael-noll.com/blog/2013/03/17/reading-and-writing-avro-files-from-the-command-line/).
=> facilitator: linter for manifests

.github/workflows/deploy-tool-build.yml
Last week, when I made the release/narnia branch, I forgot to enable the
jobs in deploy-tool-build.yml for `release/**` branches. This is causing
other PRs onto release/narnia to be unmergeable because required test
jobs don't run.
=> GH actions: enable deploy-tool-build on release/**

facilitator/src/manifest.rs
Google is a big data company, so the numeric unique IDs for GCP service
accounts don't fit into u64. This commit changes the type of the
google_service_account field of IngestionServerIdentity to Option<u128>
to make sure we can parse account IDs.
=> facilitator: use string for GCP service account ID

workflow-manager/Dockerfile, workflow-manager/build.sh, workflow-manager/main.go
Taking some ideas from #168, this builds off a Go image instead of
relying on the person building to have Go installed. It uses go mod
download to build a layer with dependencies cached.
This still relies on a build.sh run on the host, which gathers
information about the git branch. To streamline things, it combines
all the build info into a single variable.
Sets the build timestamp to local time on the build machine. This
is easier to reference when building on a dev workstation; for release
builds this will be whatever GH Actions sets, which I'm pretty sure is UTC.
Attach a label with the build info to the image. This lets us check
the metadata for an image in a registry to confirm when it was built
and what branch.
=> workflow-manager: make build more self-contained.

facilitator/src/batch.rs, facilitator/src/intake.rs, facilitator/src/transport.rs, facilitator/src/transport/gcs.rs, facilitator/src/transport/local.rs, facilitator/src/transport/s3.rs
For GETs and PUTs, log not just the bucket name, but also the key.
Remove the derive(Debug)  on OauthTokenProvider and provided a custom
Debug impl, so we don't log the tokens.
Rename the fields of OauthTokenProvider to be shorter.
=> facilitator: improve logging

terraform/main.tf, terraform/modules/data_share_processor/data_share_processor.tf, terraform/modules/kubernetes/kubernetes.tf, terraform/variables/gamlin-test.tfvars
workflow-manager allows configuring the aggregation window and grace
period. This commit plumbs variables from tfvars down to the kubernetes
module so we can tune those values, which will let us run the Narnia
test a little quicker.
=> terraform: vars for aggregation period and grace

terraform/variables/gamlin-test.tfvars
Google has brought their ingestion server online for the Narnia test.
This commit adds an entry to gamlin-test.tfvar's ingestors map for that
server. We use the ingestor label "g-enpa" because "google" would cause
us to create GCS buckets with forbidden names.
=> terraform: add Google's ingestor to gamlin-test

facilitator/src/aggregation.rs, facilitator/tests/integration_tests.rs
We were reporting the dimension of the sum part vector as the client
count instead of the number of contributing packets.
=> facilitator: fix total_individual_clients count

facilitator/src/manifest.rs, terraform/main.tf, terraform/modules/data_share_processor/data_share_processor.tf
Our role assumption policy was granting access based on the numeric
account ID of the GCP service account. Apparently, the tokens our
colleagues at Google get from GCP IAM sometimes instead contain the
service account's email address. We amend the role assumption policy so
that either will work.
More context: https://enpa-collab.slack.com/archives/C01DD6F1VG8/p1605040844399000
=> Extend ingestor writer role assumption policy

deploy-tool/main.go, facilitator/src/manifest.rs, terraform/modules/data_share_processor/data_share_processor.tf
In order for ingestors in GCP to be able to write to ingestion buckets,
they must know what AWS IAM role to assume. We were already creating the
necessary role and configuring ingestion buckets to allow it to write,
but we hadn't exposed the ARN in the specific manifest, which this
commit fixes.
=> Advertise ingestion writer role ARN from manifest

workflow-manager/main.go
Previously, we tried to use default credentials via
`config.NewEnvCredentials()`, but that only supports a subset of
possible credentialing methods. By leaving the credentials unset, I
believe we can take advantage of a wider role of possible credential
inputs, like AWS_ROLE_ARN / AWS_WEB_IDENTITY_TOKEN_FILE.
=> workflow-manager: Use default credentials.

facilitator/Cargo.lock, facilitator/Cargo.toml, facilitator/src/transport/s3.rs
Rusoto offers a "ChainProvider", which will try each of the various auth
methods available on AWS in order, and return as soon as one works. The
ChainProvider offered by Rusoto omits WebIdentityProvider, which we
need.
This change copies the implementation of ChainProvider, and adds
WebIdentityProvider to the list of providers tried.
=> facilitator: Add AWS ChainProvider for WebIDP.

facilitator/src/batch.rs, facilitator/src/lib.rs
As a debugging aid, adds a pretty-print function for byte arrays, and
uses it to print packet file digests when there is a mismatch.
=> facilitator: hex_dump packet file digests

terraform/modules/kubernetes/kubernetes.tf
The default `intake-max-age` value in workflow-manager is 1h, but we
need a wider window in order to intake Google batches (as they emit
batches hourly) and also to retry batches that might have failed for
some transient reason. This commit increases that parameter to 24 hours.
=> terraform: increase intake max age

.github/workflows/deploy-tool-build.yml
Fixes the deploy-tool CI build since GitHub broke SetEnv https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
=> Fixes the deploy-tool CI

facilitator/Dockerfile
We've found in some conditions, the bare-binary variant fails to look up
DNS. We should figure that out, but in the meantime, building a full-fat
image will probably make things work.
=> facilitator: Keep the full Alpine image.

facilitator/Cargo.lock, facilitator/Cargo.toml, facilitator/src/bin/facilitator.rs, facilitator/src/http.rs, facilitator/src/lib.rs, facilitator/src/manifest.rs
This adds a new get_url function that wraps ureq gets, turning ureq's
synthetic_errors into Results, and using anyhow to add context about
which URL failed.
This also changes the manifest reader functions to take a slice of bytes
instead of a reader.
=> facilitator: refactor manifest fetching.

facilitator/src/transport/s3.rs
We were retaining ownership of individual objects written to peer owned
buckets, making it impossible for the peer to read them. This commit
causes us to use the bucket-owner-full-control canned ACL when doing
uploads.
=> facilitator: delegate S3 object ownership to peer

workflow-manager/build.sh
At build time, we embed the branch and git commit into workflow-manager,
so it can print that when it starts up. However, the `git symbolic-ref`
invocation doesn't work when checked out to a tag rather than a branch.
That meant that our tagged releases wouldn't have an informative build
ID. This adds handling for tags.
=> workflow-manager: include tag in build info.

workflow-manager/main.go, workflow-manager/main_test.go
Kubernetes requires that object names be in lower case.
=> workflow-manager: downcase job names.

terraform/modules/gke/gke.tf
Enables a few easy-win hardening settings in GKE. Shielded nodes were suggested by the Atredis report and the rest are other things I noticed along the way. See the individual commit messages for more info.
=> Misc. hardening improvements

terraform/modules/kubernetes/kubernetes.tf, workflow-manager/main.go
This adds some baseline requests for workflow-manager and the aggregate
job. There were already requests in for facilitator. Note: These are
completely made-up numbers; we should tune the request sizes later based
on need.
=> Add more pod resource requests.

.github/workflows/deploy-tool-build.yml
The low timeout was causing some builds to fail, this fixes that.
=> Increases timeout on deploy-tool linting

terraform/main.tf, terraform/modules/gke/gke.tf, terraform/modules/gke/network.tf, terraform/network.tf
Fixes #52 
Also happens to very partially address #160 (only for the services I personally ran into while setting it up, and with caveats.)
I considered adding more restrictive egress firewall rules (the defaults are to allow all egress and no ingress) but they would probably just allow [80,443] to 0.0.0.0/0, which is so general as to seem somewhat pointless. Regardless we can still add something later on, especially once we don't have the data plane jobs fetching manifests anymore, since then we could allow only DockerHub, AWS STS and S3 access on the data plane, I think, instead of whitelisting whatever random IPs the other parties will use for manifests.
(Commit text reproduced below.)
---
Private clusters don't assign public IP addresses to individual cluster nodes. This greatly …
=> terraform: Use private GKE clusters

facilitator/src/lib.rs, facilitator/src/manifest.rs, terraform/main.tf, terraform/modules/cloud_storage_aws/cloud_storage_aws.tf, terraform/modules/cloud_storage_gcp/cloud_storage_gcp.tf, terraform/modules/data_share_processor/data_share_processor.tf, terraform/modules/fake_server_resources/fake_server_resources.tf, terraform/modules/kubernetes/kubernetes.tf, workflow-manager/main.go
This commit moves ISRG's storage from S3 to GCP, and sets up the peer
test env so that one has its ingestion and peer validation buckets in S3
and the other has all its storage in GCS. This also includes bumps to
the format versions of various manifests, though they will change some
more before we can finalize format = 1 of various documents. Finally,
facilitator and workflow-manager now accept the argument "" for
their various identity parameters, indicating that no special role
assumption or service account impersonation should take place.
=> Move storage to Google Cloud Storage

terraform/main.tf, terraform/modules/cloud_storage_gcp/bucket/bucket.tf, terraform/modules/cloud_storage_gcp/cloud_storage_gcp.tf, terraform/modules/data_share_processor/data_share_processor.tf, terraform/modules/gke/gke.tf
Refactors creation of GCS buckets into a module which does two
additional things:
- enables object lifecycle to automatically delete bucket contents
after 7 days
- enables encryption at rest with a per-data share processor KMS key
Resolves #38, #46
=> GCS object lifecycle and encryption

terraform/README.md, terraform/modules/data_share_processor/data_share_processor.tf
Creating specific manifests from Terraform was causing TF to destroy
manifests containing valid keys on each `make apply`. This also adds
a useful tip to the Terraform README.
=> Terraform: don't create specific manifests

facilitator/Dockerfile
BUILD_INFO contains a timestamp, which changes on every run of build.sh.
Putting the BUILD_INFO information early in the container meant that
caching of layers was never working. By moving BUILD_INFO lower, we can
cache everything up to the actual build of facilitator itself.
=> facilitator: Move BUILD_INFO lower in Dockerfile.

terraform/README.md, terraform/main.tf
Make sure the Prometheus provider uses credentials for the Kubernetes
cluster managed by Terraform, and not ambient credentials from ~/.kube,
which may not be for the right cluster. Additionally, we now set the
repository from which to pull the Prometheus chart so that operators
don't need to `helm add stable` outside of Terraform before deploying.
=> terraform: configure Prometheus provider

workflow-manager/main.go, workflow-manager/main_test.go
Intake Kubernetes jobs must incorporate the batch UUID name or
workflow-manager will not schedule jobs if more than one batch arrives
with the same timestamp.
Resolves #231
=> workflow-manager: use batch ID in intake job name

terraform/main.tf, terraform/modules/account_mapping/account_mapping.tf, terraform/modules/cloud_storage_gcp/bucket/bucket.tf, terraform/modules/data_share_processor/data_share_processor.tf, terraform/modules/fake_server_resources/fake_server_resources.tf, terraform/modules/gke/gke.tf, terraform/modules/gke/network.tf, terraform/modules/kubernetes/kubernetes.tf, terraform/modules/manifest/manifest.tf, terraform/network.tf
This adds explicit provider version requirements to the TF file (as recommended by documentation, and also stops TF from nagging every time about how you should add that).
It also changes all GCP resources to use the non-beta google provider. This mean not needing to add `provider = google-beta` to every single resource. For resources requiring the beta provider, that can still be added, and the two providers interoperate seamlessly (no need to `terraform import` or anything of the sort).
=> terraform: Explicitly require providers & use non-beta google by default

facilitator/src/bin/facilitator.rs, facilitator/src/config.rs, facilitator/src/manifest.rs, terraform/main.tf, terraform/modules/data_share_processor/data_share_processor.tf
Google will have one ingestion server per locality, using distinct batch
signing keys and GCP service accounts. We now will check for the
ingestor global manifest, and if it cannot be found, will fall back to a
specific manifest at a path "<instance-name>-manifest.json", i.e.,
"us-co-g-enpa-manifest.json". If there is a global manifest but it is
not a valid manifest, we still error out.
resolves #107
=> deal with non-singleton ingestors

facilitator/src/bin/facilitator.rs, facilitator/src/transport/s3.rs
During Narnia testing, we encountered cases where we failed to upload
validation batches to S3 because the ingestion batches were _just_ big
enough so that roughly ten seconds would elapse between the
CreateMultipartUpload call and the first UploadPart. We had previously
set the Hyper connection pool idle timeout to 10 seconds to avoid having
S3 close connections on us after 20 seconds, so sometimes we would lose
the race with Hyper and have uploads spuriously fail. Our fix is to
detect the case where the txn fails due to the connection getting closed
(which manifests as RusotoError::HttpDispatch) and try up to two more
times in that case. We don't retry in the face of other errors to avoid
abusing Amazon API endpoints.
Example of the error encountered:
HttpDispatch(HttpDispatchError { …
=> facilitator: retry AWS S3 requests

terraform/modules/data_share_processor/data_share_processor.tf
I noticed a bug in the construction of the bucket_access_identities map
in the case where we're not creating a paired test env.
=> terraform: typo in bucket_access_identities

facilitator/src/transport/s3.rs
We observed that every single S3 transaction being done by NCI's
facilitator containers was taking at least 30 seconds, which led me to
suspect a timeout somewhere. I think I was able to reproduce the problem
by moving my ~/.aws/ directory aside and running facilitator locally.
Sure enough, it takes 30 seconds for Rusoto to give up on connecting to
169.254.169.254 (the AWS instance metadata endpoint). The crude fix here
is to check the web identity provider before instance metadata.
=> s3: try WebIdentityProvider before instance metadata

facilitator/src/aggregation.rs, facilitator/src/transport/gcs.rs
Have the aggregation jobs log rejected packets, and also log what inputs
and outputs they are using, analogously to some very helpful logging in
the intake-batch job.
=> facilitator: improve aggregation job logs

terraform/modules/gke/gke.tf, terraform/variables/prod-us.tfvars
- add prod-us.tfvars, with correct production manifest URLs for MITRE,
Apple and NCI. Google hasn't yet confirmed their manifest endpoint
but we can bootstrap the env without the final value in place yet.
Per prior agreement, we set aggregation period to 8h and grace period
to 4h. We don't yet have any localities configured.
- make the worker node pools bigger in hopes of not running out of
compute capacity.
=> Add the env for United States production

facilitator/src/aggregation.rs, facilitator/src/bin/facilitator.rs, facilitator/src/idl.rs, facilitator/src/intake.rs, facilitator/src/lib.rs, facilitator/src/sample.rs, facilitator/src/test_utils.rs, facilitator/src/transport.rs, facilitator/src/transport/gcs.rs, facilitator/src/transport/local.rs, facilitator/src/transport/s3.rs, facilitator/tests/integration_tests.rs
This PR resolves #118. The first commit enhances the sample generation so it can drop every nth packet from the PHA batch and every mth from the facilitator batch, as well as recording expected sums and dropped packet UUIDs. The second commit reimplements aggregation such that we no longer discard whole batches if any individual validation packet is missing.
=>  Gracefully drop mismatching packets during batch aggregation

terraform/main.tf, terraform/modules/data_share_processor/data_share_processor.tf, terraform/modules/kubernetes/kubernetes.tf, terraform/variables/prod-us.tfvars
We pin the prod-us deployment of the application to version 0.5.0 of
`prio-workflow-manager` and `prio-facilitator`. This commit also plumbs
arguments for container image versions and image repository all the way
from kubernetes.tf to main.tf.
=> terraform: pin prod-us to 0.5.0 images

facilitator/src/bin/facilitator.rs
clap has a macro value_t that lets us skip much of the boilerplate:
https://docs.rs/clap/2.33.3/clap/macro.value_t.html
=> Simplify call to generate_ingestion_sample.

facilitator/src/aggregation.rs, facilitator/src/bin/facilitator.rs, facilitator/src/idl.rs, facilitator/src/sample.rs
We short circuited jsha's review on #265 in order to accelerate release
of production code to our partners. This PR addresses those comments.
- use type annotations to make code more obvious
- remove nested expressions in `match` statements
- remove unused `Ord` and `PartialOrd` implementations from idl.rs
- fix typo in sample.rs
=> facilitator: jsha review feedback from #265

terraform/variables/prod-us.tfvars
Adds a new test/fake locality for integration testing with peer
production and pre-production deloyments. Updates peer manifest endpoint
to point at NCI test deployment.
=> prod-us: add ta-ta locality for testing

workflow-manager/main.go
During development and testing, we forced the ImagePullPolicy to Always
in an effort to avoid the risk of stale images. In production, we don't
need to fetch an image from DockerHub every single time we spawn the
facilitator.
=> workflow-manager: set ImagePullPolicy=IfNotPresent

workflow-manager/main.go
facilitator jobs, whether intake-batch or aggregate, are
single-threaded, and during testing with large batches (> 100 MB
ingestion batches), I observed that `intake-batch` jobs quickly reach
~0.7 CPUs (which is the maximum currently allowed by the jobs
workflow-manager creates) and stay there until they are done. By raising
the CPU request/limit from 0.5/0.7 to 1.0/1.5, we should achieve a
speedup of 0.3 / 0.7 = ~43%. Individual jobs are not going to use any
more than 1.0 CPU because there's no multithreading within an individual
`facilitator` job, so the 1.5 maximum is just a healthy margin of error.
I haven't observed extraordinary memory usage, meaning the 500 MB memory
request we currently have will suffice, provided we don't see ingestion
batches larger than that.
=> workflow-manager: request 1.0 CPU for facilitator

terraform/variables/prod-us.tfvars
Adds infrastructure for `us-ct` to the `prod-us` deployment, and updates
the peer data share processor manifest base URL to NCI's production
deployment.
=> terraform: add us-ct deployment to prod-us

terraform/modules/gke/gke.tf
We encountered a problem where GCP implicitly limits clusters with fewer
than 10 nodes to 10,000 jobs per namespace, a limit we ran up against
once we started receiving batches from Connecticut. This change forces
the node pool to create at least 4 VMs in each of three zones, bumping
our cluster size high enough that our job limit is now 50,000.
=> terraform: force worker pool size to 12

workflow-manager/batchpath/batchpath.go
The new version of workflow-manager introduced in #292 writes out task
marker objects to the own validation bucket to track which intake and
aggregation tasks have been scheduled. This commit teaches the old
version of workflow-manager to gracefully ignore any such files, to give
us something safe to roll back to in case deploying #292 to production
fails in such a way that leaves task markers behind.
=> workflow-manager: ignore task markers

workflow-manager/bucket/bucket.go, workflow-manager/kubernetes/kubernetes.go, workflow-manager/task/task.go, workflow-manager/utils/utils.go
use context.Context to set a 30s timeout on GCP and Kubernetes API
calls.
=> workflow-manager: add timeouts to context.Contexts

terraform/variables/prod-us.tfvars, terraform/variables/staging-facil.tfvars, terraform/variables/staging-pha.tfvars
Per estimates described in #300, this commit configures appropriately
sized worker pools for `us-ct` and `us-md`, and pins the `prod-us`
deployment to `prio-facilitator` and `prio-workflow-manager` 0.6.0.
=> terraform: configure worker pools and pin 0.6.0

terraform/modules/kubernetes/kubernetes.tf
Raises memory and CPU limits for the workflow-manager so that long lists
of Kubernetes jobs and cloud storage bucket listings can fit safely in
memory. The CPU limits are raised just to let the workflow-manager go a
little faster, though realistically it's going to spend most of its time
waiting on API calls.
=> terraform: adjust workflow-manager resource limits

facilitator/src/aggregation.rs, facilitator/src/bin/facilitator.rs, facilitator/src/intake.rs, facilitator/src/task.rs, facilitator/src/task/pubsub.rs, facilitator/src/task/sqs.rs, facilitator/tests/integration_tests.rs
Adds methods to the `TaskQueue` trait that allow extending task
deadlines (aka ack deadline in GCP PubSub or visibility timeout in AWS
SQS) when tassk are running long. Also adds callback parameters to
`BatchIntaker::generate_validation_share` and
`BatchAggregator::generate_sum_part` which fire periodically to give a
caller an opportunity to evaluate how much time has elapsed since the
start of the task and extend deadlines as necessary. See #308 for more
context on why this is needed.
Resolves #308
=> facilitator: extend task deadlines

workflow-manager/main.go, workflow-manager/main_test.go, workflow-manager/monitor/monitor.go, workflow-manager/monitor/monitor_test.go
Fixes a bug where metrics were being pushed to the pushgateway at the
beginning of the workflow-manager instead of the end, such that no
metrics were pushed before being gathered locally.
Additionally adds new gauges for:
- number of tasks scheduled
- number of tasks detected but skipped due to age, task marker or
existing k8s job
- time of last successful and failed runs
- how long it took to run workflow-manager
All of these are gauges, in keeping with the advice in Prometheus
documentation (https://prometheus.io/docs/practices/instrumentation).
Because this is a batch job, we can't meaningfully use anything but
gauges, as other collector types would get reset with each run of
workflow-manager.
Existing metrics are renamed to prefix them with `workflow_manager_`,
and all metrics are …
=> workflow-manager: additional metrics

workflow-manager/bucket/bucket.go, workflow-manager/main.go, workflow-manager/task/task.go
We observed workflow-manager failing in the `us-md-apple` instance
because we were hitting timeouts enumerating the contents of GCS
buckets. This is because the `list` API on buckets is paginated
(https://cloud.google.com/storage/docs/json_api/v1/buckets/list), which
the Go SDK handles by returning an `ObjectIterator` from
`BucketHandle.Objects()`. However you can only provide a
`context.Context` to the initial call to `Objects()`, and each
subsequent call to `ObjectIterator.next()` is subject to the same
initial timeout. There's no way to reset the timeout on a
`context.Context` that I can find, so I believe the thing to do is to
raise the timeout for this particular operation, which we understand
actually does take longer than 30 seconds, to 120 seconds.
Additionally, while looking into …
=> workflow-manager: relax timeout on GCS object list

terraform/main.tf, terraform/modules/monitoring/monitoring.tf, terraform/variables/prod-us.tfvars
During a recent production incident, we saw that prometheus-server
entered a crashloop because it filled up the 8 GB persistent volume it
used to store metrics. This commit resolves that by:
- creating regional persistent disks for prometheus-server and
prometheus-alertmanager, with replicas in two zones
- making those disks much bigger than before (the minimum size for a
GCE regional disk is 200 GB, but we use an even bigger one in
prod-us)
- constructing our own Kubernetes PersistentVolumes and
PersistentVolumeClaims since the Prometheus Helm chart can only
manage zonal disks
#233 mentions introducing regional storage for Prometheus Alertmanager. I opted not to do that, because Alertmanager doesn't need a lot of storage (all it stores are alert silences), so allocating a whole 200 GB …
=> terraform: larger and regional prometheus disks

terraform/modules/kubernetes/kubernetes.tf, terraform/modules/monitoring/monitoring.tf, workflow-manager/main.go
`workflow-manager` metrics were grouped by namespace (hence, locality),
but metrics emitted by either ingestor's `workflow-manager` were going
to the same time series, leaving us unable to distinguish between the
health of Apple vs. g-enpa task schedulers. This commit adds a new
grouping to metrics pushed by `workflow-manager` for ingestor name, and
amends Terraform to pass that ingestor name into the `workflow-manager`.
This also fixes a problem with the `prometheus-server` deployment: by
default, the Prometheus helm chart creates a Kubernetes deployment for
`prometheus-server` with an update strategy of `RollingUpdate`. This
doesn't work with a persistent volume because it cannot be shared across
two revisions during an update. We opt into the `Recreate` strategy to
work around this. …
=> workflow-manager: label metrics by ingestor

facilitator/Cargo.lock, facilitator/Cargo.toml, facilitator/src/aggregation.rs, facilitator/src/aws_credentials.rs, facilitator/src/bin/facilitator.rs, facilitator/src/intake.rs, facilitator/src/lib.rs, facilitator/src/metrics.rs, facilitator/src/transport/s3.rs, terraform/modules/kubernetes/kubernetes.tf
This PR sets up basic metrics delivery from the `facilitator` for the `intake-batch` and `aggregate` deployments.
- I used [`warp`](https://crates.io/warp) to implement the metrics endpoint, which required spawning a task into a `tokio::runtime::Runtime`. `tokio` just released their 1.0 crate, so I updated our dependency, and also updated a number of other dependencies (such as `hyper` and `rusoto`) to move to versions which use `tokio` 1.0. We used to have several versions `hyper`, `rustls`, `tokio` and other dependencies compiled into the crate, but now we pull in far fewer distinct versions.
- When the `intake-batch-worker` or `aggregate-worker` subcommands are invoked, `facilitator` now listens on a configurable port for GET requests to the `/metrics` endpoint
- In Terraform, we now …
=> Scrape basic faciliator metrics

terraform/modules/account_mapping/account_mapping.tf, terraform/modules/kubernetes/kubernetes.tf, terraform/modules/locality_kubernetes/kubernetes.tf, terraform/modules/monitoring/monitoring.tf
We install the stackdriver-exporter Helm chart to forward GCP PubSub
metrics (or any other GCP metrics we want) into Prometheus.
=> terraform: install stackdriver-exporter

terraform/main.tf, terraform/modules/data_share_processor/data_share_processor.tf, terraform/modules/kubernetes/kubernetes.tf
The `intake-max-age` parameter to `workflow-manager` had been hard-coded
to 24h. This is longer than makes sense given our aggregation window of
8 hours in production, and in any case this should be configurable,
since being able to tune that parameter has already helped us out of a
couple of different incidents. This commit adds a top level Terraform
variable for `intake-max-age`, and sets the default to the more
reasonable value of six hours.
Resolves #331
=> terraform: configurable intake-max-age

terraform/modules/account_mapping/account_mapping.tf
`account_mapping` incorrectly used the non-unique GCP project name
instead of project ID, which would cause us to incorrectly construct
Kubernetes SA <-> GCP SA workload identity bindings.
=> terraform: use GCP project *ID* instead of name

terraform/modules/monitoring/monitoring.tf
Another GCP project *name* vs. *ID* bug: `stackdriver-exporter` needs
the GCP project ID so it can authenticate to the monitoring API. We were
providing the name, which is not the same value in staging.
=> terraform: provide GCP project *ID* to stackdriver

terraform/variables/prod-us.tfvars
Adds an instance to support `us-va`. Our understanding is that we expect
a load similar to MD or CT, and so we allocate the same numbers of
workers.
=> terraform: deploy us-va in prod-us

docs/monitoring.md, terraform/README.md, terraform/main.tf, terraform/modules/monitoring/monitoring.tf, terraform/modules/monitoring/prometheus_alerting_rules.yml, terraform/modules/pubsub/pubsub.tf, terraform/variables/prod-us.tfvars, terraform/variables/staging-facil.tfvars, terraform/variables/staging-pha.tfvars
Configures the Prometheus Helm chart to include alerting rules defined
in a standalone YAML file. Updates `prometheus-alertmanager`
configuration so that only alerts with `severity: page` are routed to
the Victorops receiver.
We now have the following alerts set up:
- page if any `workflow-manager` instance has not run in the last 30
minutes
- page if more than 95% of intake tasks fail during the last hour
- page if more than 95% of aggregate tasks fail during the last 8 hours
- page if any PubSub queue has undelivered messages for an entire hour
=> terraform: basic Prometheus alerting rules

facilitator/src/aggregation.rs, facilitator/src/bin/facilitator.rs, facilitator/src/intake.rs, facilitator/src/metrics.rs, facilitator/tests/integration_tests.rs
We are losing whole aggregations because one peer validation batch out
of ~900 happens to have an invalid signature or an incorrect packet file
digest in its header. We should still be able to aggregate the other 899
batches in such a case. We now continue with the aggregation if an
individual call to `BatchAggregator::aggregate_share()` fails.
We also now gather metrics on how many invalid own and peer validation
batches are encountered during an aggregation. This will enable us to
get a better idea of how often the bug that caused invalid validation
batches occurs.
Resolves #343
Resolves #345
=> facilitator: don't abort integration for bad batch

facilitator/Cargo.lock, facilitator/Cargo.toml, facilitator/src/config.rs, facilitator/src/gcp_oauth.rs, facilitator/src/http.rs, facilitator/src/manifest.rs, facilitator/src/task/pubsub.rs, facilitator/src/transport/gcs.rs, facilitator/src/transport/s3.rs
The change caused an issue like this:
```
gs://prio-timg-dev-facil-narnia-ingestor-1-ingestion/kittens-seen%2F2021%2F02%2F04%2F17%2F16%2Fba53ce56-f4a1-4e75-bee5-88ffa33d656b.batch
```
After testing this in a dev environment the problem has gone away.
The issue was that the object name was getting urlencoded twice, which when Google decoded it it still left one round of encoding in it.
=> ureq version bump to 2.0

facilitator/src/manifest.rs
Fixes https://github.com/abetterinternet/prio-server/issues/266.
Now when running `facilitator lint-manifest` on the manifest from #266, the output is:
```
Error: failed to decode JSON manifest
Caused by:
unknown field `google-service-account`, expected one of `aws-iam-entity`, `gcp-service-account-id`, `gcp-service-account-email` at line 5 column 28
```
The changes made to the other test cases in this PR were to get them passing for the documented reason. For instance, the comment above a manifest we expect to be invalid may say something like `// No format key`, however, the manifest was also invalid due to an incorrect field name, missing comma, etc.
=> Reject unexpected manifest keys

terraform/modules/kubernetes/kubernetes.tf
On 2021/2/4, we saw some `workflow-manager` jobs fail with OOM, because
the arrival of new aggregations on the Apple side increased the
steady-state count of objects in ingestion buckets, eventually pushing
those `workflow-manager` jobs over the existing 2 Gi memory limit. This
was resolved by manually bumping the failing cronjobs' memory limits to
4 Gi. This commit makes a more permanent change to set the memory limits
to 8 Gi (because I _really_ don't want to get paged about this again). A
more robust change to limit the memory footprint of `workflow-manager`
will come when we address #162.
=> terraform: set workflow-manager memory limit to 8G

terraform/modules/kubernetes/kubernetes.tf, workflow-manager/main.go, workflow-manager/main_test.go
Now that Kubernetes job existence is no longer used to determine if any
tasks have been scheduled, `workflow-manager` is absolved of the need to
list Kubernetes jobs. We also remove the Kubernetes role which granted
it and facilitators permission to list and get namespaces, pods and
jobs.
Resolves #306
=> workflow-manager: stop listing Kubernetes jobs

.github/dependabot.yml
We're relying on a bunch of dependencies, let's add dependabot (https://github.blog/2020-06-01-keep-all-your-packages-up-to-date-with-dependabot/) configuration to our source so we can use the automated dependency updates offered by dependabot.
=> Add dependabot configuration for all of our currently used packages

facilitator/src/transport/gcs.rs
This commit increases the timeout used for GCS uploads to 120 seconds
from 10 seconds. 10 seconds appeared to suffice for uploading to GCS
from within GCP, but log analysis shows that NCI intake jobs were
sometimes failing because of this timeout, in a way that your humble
commit author believes was ultimately causing the aggregation failures
we have been seeing.
=> facilitator: use long timeouts on GCS uploads

terraform/variables/prod-us.tfvars
The theory about duplicate message delivery turned out to be wrong, and
scaling down our worker deployments just led to unnecessary pages
overnight. This commit restores prod-us intake-batch and aggregate
worker pools to their previous sizes, effectively reverting
36e8e62a50aa4db592f5b00443cd3e81ed74c89a.
=> terraform: restore prod-us deployment replicas

facilitator/src/aggregation.rs, facilitator/tests/integration_tests.rs
The change in af63ea39 was based on faulty reasoning: you can't drop
individual batches from the aggregation if the other side hasn't also
dropped those batches, because otherwise their sum part will include
shares that aren't matched by ours, introducing (as @winstrom put it)
"infinite noise". What's worse, because I had punted on differentiating
recoverable errors (e.g., getting a 500 response from GCS: if we retry,
it'll probably work) from unrecoverable ones (e.g., an invalid
signature), we effectively stopped retrying aggregation tasks, degrading
our instance's output.
This commit partially revers af63ea39, restoring the prior behavior
where a single error causes facilitator to abort the entire aggregation.
This means that PubSub (or SQS) will redeliver the task message, so we
will …
=> facilitator: fail aggregations on bad batch

facilitator/src/bin/facilitator.rs, facilitator/src/http.rs, facilitator/src/manifest.rs, facilitator/src/sample.rs, facilitator/src/task/pubsub.rs, facilitator/src/task/sqs.rs
These were throwing warnings in clippy. Getting rid of them might make clippy outputs easier to read.
=> Get rid of all clippy warnings

facilitator/src/aws_credentials.rs, facilitator/src/task/sqs.rs, facilitator/src/transport/s3.rs
Analysis of NCI logs shows that requests to SQS can sometimes fail
because of DNS lookup failures. Further, S3 requests sometimes fail in
the credentials phase due to DNS failures, which doesn't get caught by
existing retry mechanisms because of how Rusoto bubbles up errors (see
comment in `aws_credentials.rs::retry_request`). We now will retry both
SQS client requests, and check for a CredentialsError that _probably_
wraps an HttpDispatchError so we can retry requests to STS.
Additionally, to ensure we can accurately detect the failure when using
the webidp_provider (which is what NCI does), we short circuit the chain
of providers in `ChainProvider::chain_provider_credentials`.
=> facilitator: retries on SQS and STS requests

facilitator/src/transport/gcs.rs
use .timeout to set a 2m timeout on the whole transaction rather than
piecemeal on reads or writes.
=> facilitator: GCS client timeouts

terraform/main.tf, terraform/modules/data_share_processor/data_share_processor.tf, terraform/modules/kubernetes/kubernetes.tf, terraform/variables/staging-facil.tfvars, terraform/variables/staging-pha.tfvars, workflow-manager/main.go
After the 2021/2/18 production deploy, we encountered alerts because the
`workflow_manager_last_success_seconds` metric was not being set in
`ta-ta-apple`, `ta-ta-g-enpa` or `us-va-g-enpa`. This is because no data
comes into those instances, and so no aggregation IDs are discovered in
their ingestion buckets, and due to a bug introduced by #370, the metric
was being set only if there were tasks to schedule. We had the same
problem with the `workflow_manager_runtime_seconds` metric, which would
get set too many times during a run of `workflow-manager` (though the
last value that would get set was correct).
We now also configure the staging environment to _not_ create a
`sample-maker` cronjob in one of the three localities it creates, so
that going forward, our staging environment can …
=> workflow-manager: set success metric

facilitator/Dockerfile, facilitator/src/bin/facilitator.rs
NCI was seeing DNS failures which I think could be caused by Alpine's
musl DNS resolver. Here we build the facilitator container with the
default Rust image, which is Debian based, which uses libc.
https://stackoverflow.com/questions/65181012/does-alpine-have-known-dns-issue-within-kubernetes
=> facilitator: build on default (Debian) Rust image

facilitator/src/transport/gcs.rs
We have observed some failures in aggregations that are caused by
timeouts when *reading* from GCS (this on top of previously observed
timeouts when *writing*). This commit extrends read timeouts to 2
minutes.
=> facilitator: relax GCS read timeout

terraform/modules/monitoring/prometheus_alerting_rules.yml, terraform/variables/prod-us.tfvars
Configures prod-us/us-ca deployment, and adjusts the `task_queue_growth` alert to reduce spurious pages. See commit messages for capacity planning rationale and additional commentary.
=> Turn on us-ca in prod-us

terraform/main.tf, terraform/modules/gke/gke.tf, terraform/variables/prod-us.tfvars, terraform/variables/staging-facil.tfvars, terraform/variables/staging-pha.tfvars
We're spinning up a LOT of nodes and big machines for dev environments and staging, we don't need to do this. This PR surfaces the variables used when constructing the GKE environment.
=> Allow us to define what kind of machines and node count for GKE

terraform/modules/monitoring/prometheus_alerting_rules.yml
We now define two separate alerts for task queue growth, one for intake
queues and one for aggregations. The rationale is that aggregation tasks
generally take much, much longer than intake tasks, especially in
localities which submit a lot of data like `us-ca`. We now alert if any
intake task queue is non-empty for more than 30 minutes: since
workflow-manager runs and schedules new intakes every 10 minutes, we
expect those queues to empty more frequently. We alert if aggregations
take longer than 6 hours, a figure informed by historical performance of
us-ca-apple aggregation tasks.
This is implemented by matching on the suffix of the `subscription_id`
label of the Stackdriver PubSub metric. I would prefer to match on
someting more explicit, but I can't obviously see how: I tried adding a …
=> terraform: split task queue growth alerts

terraform/Makefile, terraform/main.tf, terraform/modules/fake_server_resources/fake_server_resources.tf, terraform/modules/portal_server_resources/portal_server_resources.tf, terraform/variables/staging-pha.tfvars
- Fixes the Makefile
- Adds a new target called `portal_server_resources`.
- Changes when and how `has_test_environment` is set to true. Effectively this doesn't change the behavior of `has_test_environment`. But makes it dependent on the `fake_server_resources` module, which is what we want to get the output to update when doing `apply bootstrap`.
This is a new module that creates the portal server. When the "deployment" (full dual-testing peer environments) are being deployed, this will create a fake "portal server/collector" for the aggregations of facil and pha. This isn't the **best** solution because ideally these would live inside the one environment (usually facil) that has the integration-tester set.
However, trying to get to that ideal solution through terraform seems difficult …
=> Terraform changes to allow for integration testing

.github/workflows/ci-build.yml
Removes our dependency on rust nightly for code coverage. Although `RUSTC_BOOTSTRAP: '1'` seemingly makes a stable installation into a nightly one. 
This fixes the random pem & s3 test failures we've been seeing the past few days.
=> Fixes the coverage report for facilitator

facilitator/Cargo.toml, facilitator/src/aws_credentials.rs, facilitator/src/bin/facilitator.rs, facilitator/src/config.rs, facilitator/src/lib.rs, facilitator/src/task/sqs.rs, facilitator/src/transport/s3.rs
NCI has been running a `facilitator` forked from tag 0.6.2 for some time now, and I have been making targeted hotfixes on `release/0.6.2-nci` to minimize risk to NCI's deployment. This PR brings `main` to a state where it can safely be deployed to NCI and eventually MITRE's AWS deployments. See the individual commit messages for details on what changed and the motivation.
=> Sync main with bugfixes on release/0.6.2-nci

terraform/main.tf, terraform/modules/data_share_processor/data_share_processor.tf, terraform/modules/fake_server_resources/fake_server_resources.tf, terraform/variables/prod-us.tfvars, terraform/variables/staging-facil.tfvars, terraform/variables/staging-pha.tfvars
We can now configure manifest base URLs for the peer data share
processor and portal server on a per-locality basis. Specifically, this
enables us to configure the `ta-ta` locality in production to exchange
data with the staging/test environments operated by our colleagues at
the NCI and MITRE.
Resolves #60
This isn't deployable right now because test-en-analytics.cancer.gov isn't available. NCI is currently rebuilding their test env. We also now repeat some amount of information in each locality. It'd be nice to be able to specify default peer and portal server manifest base URLs to avoid repetition, but I opted to do what would yield the simplest Terraform, since our modules are already kind of complicated.
=> terraform: support multiple peer DSPs

deploy-tool/main.go
Likely due to a typo, we were not printing the error on failure.
=> deploy-tool: print error when key generation fails

terraform/variables/prod-us.tfvars
We got paged on 2021/3/10 because the `us-ut/intake-batch-apple`
deployment wasn't keeping up with the incoming tasks because of a spike
in traffic. I resolved that by manually scaling the deployment up to 8
workers, from 5. We observed another similar spike in incoming ingestion
batches around 4 AM PST 2021/3/11, so I want to keep the 8 workers until
we get around to autoscaling the workers (#484).
=> terraform: provision 8 us-ut-apple intake workers

terraform/variables/prod-us.tfvars
Capacity planning rationale: New Mexico's population of approximately
2.1 million should be manageable with a CT-sized deployment.
=> terraform: deploy us-nm locality in prod-us

facilitator/Cargo.lock, facilitator/Cargo.toml, facilitator/README.md, facilitator/src/aggregation.rs, facilitator/src/aws_credentials.rs, facilitator/src/batch.rs, facilitator/src/bin/facilitator.rs, facilitator/src/gcp_oauth.rs, facilitator/src/http.rs, facilitator/src/intake.rs, facilitator/src/lib.rs, facilitator/src/metrics.rs, facilitator/src/task.rs, facilitator/src/task/pubsub.rs, facilitator/src/task/sqs.rs, facilitator/src/transport.rs, facilitator/src/transport/gcs.rs, facilitator/src/transport/local.rs, facilitator/src/transport/s3.rs, facilitator/src/work_queue.rs, facilitator/tests/integration_tests.rs, terraform/main.tf, terraform/modules/data_share_processor/data_share_processor.tf, terraform/modules/kubernetes/kubernetes.tf, terraform/variables/prod-us.tfvars, terraform/variables/staging-facil.tfvars, terraform/variables/staging-pha.tfvars
We observed that in NCI's production deployment, us-ca-apple
individual aggregation tasks are often taking more than eight hours to
run, which means that even adding more aggregation workers won't speed
things up. We schedule aggregations to run every eight hours, making it
impossible for NCI to keep up with incoming work.
To ameliorate this, this commit refactors the aggregation task handler
so that it can spawn multiple threads and sum over individual batches in
parallel. The threads are managed using the `WorkQueue` struct, which
implements a no-producer, multiple-consumer work queue. I say
"no-producer" because it doesn't support an "enqueue" method as you
might see in most pub/sub implementations, and instead expects the
entire list of jobs to be available at the creation of the …
=> facilitator: multi-threaded aggregation

terraform/modules/kubernetes/kubernetes.tf, terraform/modules/monitoring/monitoring.tf
Some of the resources created in Terraform can have metadata or label
attributes set at runtime by GKE. This results in `terraform apply`
performing benign but unnecessary modifications to some resources.
Typically, Terraform will remove some label that GKE will then later
automatically re-apply. However, these benign modifications pollute the
output of `terraform plan` and `apply` with irrelevant noise, which
makes it harder for an operator to pick out the real changes being
applied.
This commit adds a few `lifecycle` blocks to instruct `terraform` to
ignore certain changes:
- "environment" annotation on `workflow-manager` job template
- "cloud.google.com/neg" annotation on intake and aggregate k8s
services
- labels on the GCE persistent disk that backs Prometheus
=> terraform: reduce apply noise

terraform/modules/monitoring/prometheus_alerting_rules.yml
We are observing a lot of unactionable alerts for task queue growth. On
the intake side, these represent periodic but normal spikes in incoming
ingestion batches which can be handled without additional capacity but
not within 30 minutes. On the aggregate side, it just seems that
aggregations are taking a long time, especially in us-ca-apple. In
anticipation of deploying autoscaling and parallelized aggregations,
which will amelioriate both of these situations, this commit relaxes the
alerting rules to allow more time for workers to catch up.
=> terraform: relax prometheus alerting rules

facilitator/src/aws_credentials.rs, facilitator/src/bin/facilitator.rs, facilitator/src/gcp_oauth.rs, facilitator/src/logging.rs
Extends `log::Record` so we can also log Rust module path, source file,
source line and ThreadId in log messages, if they are available. Also
adds some `debug!` logs around handling of various Oauth tokens to make
it easier to tell when a credential has expired.
=> facilitator: add structured log fields

facilitator/src/aggregation.rs, facilitator/src/batch.rs, facilitator/src/bin/facilitator.rs, facilitator/src/intake.rs, facilitator/src/metrics.rs, facilitator/tests/integration_tests.rs, terraform/modules/kubernetes/kubernetes.tf
Adds a --permissive flag to intake-batch and aggregate subcommands,
which casuses facilitator to log problems like invalid signatures or bad
packet_file_digest, but not to abort batch processing.
This change also lowers recording of metrics about invalid batch
signatures or measurements into `batch::BatchReader`.
Resolves #542
=> facilitator: permissive mode

facilitator/Cargo.lock, facilitator/Cargo.toml, facilitator/src/aggregation.rs, facilitator/src/bin/facilitator.rs, facilitator/src/idl.rs, facilitator/src/intake.rs, facilitator/src/sample.rs, facilitator/src/test_utils.rs, facilitator/tests/integration_tests.rs
Adopts the updated `libprio-rs` API to better discriminate between
failures of `prio::server::Server::generate_verification_message` so
that a better error message can be logged if an input share is rejected
due to a packet encryption key mismatch.
Resolves #550
=> facilitator: better error on decryption failure

terraform/variables/prod-us.tfvars
Bumps containers to the latest release. Additionally, brings intake
worker replica counts in line with what's currently deployed in prod.
=> terraform: pin 0.6.12 container images in prod-us

facilitator/README.md, facilitator/src/bin/facilitator.rs
Fixes bugs in argument handling that made it impossible to run
`facilitator generate-ingestion-sample` outside of the Kubernetes
context.
This PR is stacked on top of #559
=> facilitator: fix `generate-ingestion-sample` args

facilitator/Cargo.lock, facilitator/Cargo.toml, facilitator/src/aggregation.rs, facilitator/src/aws_credentials.rs, facilitator/src/batch.rs, facilitator/src/bin/facilitator.rs, facilitator/src/gcp_oauth.rs, facilitator/src/intake.rs, facilitator/src/logging.rs, facilitator/src/manifest.rs, facilitator/src/metrics.rs, facilitator/src/sample.rs, facilitator/src/task/pubsub.rs, facilitator/src/task/sqs.rs, facilitator/src/test_utils.rs, facilitator/src/transport/gcs.rs, facilitator/src/transport/s3.rs, facilitator/tests/integration_tests.rs
We adopt the `slog-rs` family of crates for structured logging. `slog`
allows us to create trees of `Loggers` and `Drains`. `Logger`s can be
annotated with key-value pairs and then every message logged through
that `Logger` will themselves be annotated with the k-v pairs. Further,
the `slog` macros `info`, `error`, etc. allow adding arbitrary
additional k-v pairs to individual events. This lets us emit structured
log messages which can then be searched in something like the GCP Log
Explorer. `Drain`s can be configured to format log records in different
manners. We use `slog_json` to emit structured JSON logs, `slog_term` to
pretty print messages to a tty or a much simpler decorator for use in
tests.
`slog`'s model is that you create a root `Logger`, and then create a
tree of child loggers …
=> facilitator: use slog for structured logging

facilitator/src/bin/facilitator.rs, facilitator/src/intake.rs, facilitator/src/logging.rs, facilitator/src/task.rs, facilitator/tests/integration_tests.rs
Augments `intake::BatchIntaker` with a `slog::Logger` field, to which we
attach specialized labels.
Also provides a `slog::Value` implementation on `task::TaskHandle` so
that `TaskHandle<T>` values can easily be inserted into events.
Relates to #546
=> facilitator: structured logging in intake-batch

facilitator/src/bin/facilitator.rs, facilitator/src/intake.rs, facilitator/src/sample.rs, facilitator/tests/integration_tests.rs
Augments `SampleGenerator` so that it uses `slog::Logger` to emit
structured log events with rich annotations.
Part of #546
=> facilitator: structured logging for sample

.github/workflows/ci-build.yml, facilitator/src/batch.rs, facilitator/src/bin/facilitator.rs, facilitator/src/config.rs, facilitator/src/idl.rs, facilitator/src/intake.rs, facilitator/src/logging.rs, facilitator/src/manifest.rs, facilitator/src/sample.rs, facilitator/src/task.rs, facilitator/src/transport.rs, facilitator/src/transport/gcs.rs, facilitator/tests/integration_tests.rs
We previously were using the
[clippy-check](https://github.com/actions-rs/clippy-check) GitHub Action
to run clippy on changes. There's two problems with this:
1 - Because our `Cargo.toml` isn't at the root of the repo,
`clippy-check` can't post clippy results into the PR as comments
(see #69 and
https://github.com/actions-rs/clippy-check/issues/28#issuecomment-680401392)
2 - We recently set `GITHUB_TOKEN` to be readonly at the
`abetterinternet` level to mitigate potential security problems.
`clippy-check` requires write permissions to post results.
I'd prefer to keep the `GITHUB_TOKEN` passed to actions readonly, and
since the results wrangling never worked anyway, we can opt out of it.
Now, instead of using the action, we just run `cargo clippy` directly
and fail the build if any …
=> actions: invoke cargo-clippy directly

facilitator/Cargo.lock, facilitator/Cargo.toml, facilitator/src/aws_credentials.rs, facilitator/src/gcp_oauth.rs, facilitator/src/http.rs, facilitator/src/lib.rs, facilitator/src/retries.rs, facilitator/src/task/pubsub.rs, facilitator/src/transport/gcs.rs
In order to be more robust against transient failures in cloud APIs, we
introduce a `RetryingAgent` which uses the `backoff` crate to resend
failed HTTP requests with exponential backoff if the failure is
determined to be transient (e.g., an HTTP 503). The `RetryingAgent` is
adopted throughout the crate, meaning we now get retries when:
- fetching peer JSON manifests
- pulling messagesfrom GCP PubSub subscriptions
- reading or writing to Google Cloud Storage
- obtaining Oauth tokens from the GKE metadata service or IAM API
We should also record Prometheus metrics about retryable request
failures, which will happen in a future PR.
This change doesn't help with AWS API clients (S3, SQS and IAM) because
they do not use our `ureq` based HTTP client but rather Rusoto (and that
in turn uses …
=> facilitator: introduce `http::RetryingAgent`

facilitator/Cargo.lock, facilitator/Cargo.toml, facilitator/src/aws_credentials.rs
Adapts `aws_credentials::retry_request` to use mod `retries` (and hence
`backoff::ExponentialBackoff` so that we get more graceful retry
behavior, in line with AWS developer guidelines. Additionally, our
assessment of which errors are retryable is more sophisticated: we now
retry on all credential fetch failures, on server errors (i.e., HTTP
5xx) and when throttled.
Resolves #41, #354
=> facilitator: retries w/ backoff for AWS

facilitator/src/aggregation.rs, facilitator/src/bin/facilitator.rs, facilitator/src/intake.rs, facilitator/src/logging.rs, facilitator/src/sample.rs, facilitator/src/transport/gcs.rs, facilitator/src/transport/s3.rs
Per @jsha's suggestion in #595, we now define the various `EVENT_KEY_*`
constants in the `logging::event` module, allowing us to rename the
constants from `EVENT_KEY_THING` to just `THING`.
=> facilitator: move event keys to `logging::event`

facilitator/src/bin/facilitator.rs, facilitator/src/logging.rs, facilitator/src/task/pubsub.rs, facilitator/src/task/sqs.rs
Augments `task::sqs::AwsSqsTaskQueue` and
`task::pubsub::GcpPubSubTaskQueue` to use `slog::Logger` to log
structured events.
Part of #546
=> facilitator: use slogger in TaskQueue impls

facilitator/src/aws_credentials.rs, facilitator/src/bin/facilitator.rs, facilitator/src/gcp_oauth.rs, facilitator/src/task/pubsub.rs, facilitator/src/transport/gcs.rs
Plumbs `slog::Logger` into `gcp_oauth` and `aws_credentials` modules.
Part of #546
=> facilitator: use `slog::Logger` in cred providers

facilitator/src/aws_credentials.rs, facilitator/src/bin/facilitator.rs, facilitator/src/gcp_oauth.rs, facilitator/src/http.rs, facilitator/src/manifest.rs, facilitator/src/task/pubsub.rs, facilitator/src/transport/gcs.rs
Plumbs structured logging into `http::RetryingAgent`, requiring the same
to be passed through other modules that depend on `RetryingAgent`.
`RetryingAgent::logger` isn't yet used; that will come in a subsequent
PR that passes the logger into `retries::retry_request`.
Part of #546
=> facilitator: use `slog::Logger` in `http` module

facilitator/Cargo.toml, facilitator/src/transport/s3.rs
We hack around a situation where S3 reports a failure with HTTP status
200 OK, causing Rusoto to report success.
See https://github.com/rusoto/rusoto/issues/1936 for details.
=> facilitator: hack to detect S3 upload failure

facilitator/src/aws_credentials.rs, facilitator/src/gcp_oauth.rs, facilitator/src/http.rs, facilitator/src/retries.rs, facilitator/src/task/pubsub.rs, facilitator/src/transport/gcs.rs, facilitator/src/transport/s3.rs
`retries::retry_request_with_params` was not logging the retryable error
it encountered. Additionally, this commit changes the log level on
retryable erors to `warn!` so that such errors will stand out more.
=> facilitator: log retryable errors

facilitator/src/bin/facilitator.rs, facilitator/src/manifest.rs, terraform/modules/kubernetes/kubernetes.tf
The `intake-batch`, `intake-batch-worker`, `aggregate` and
`aggregate-worker` subcommands on `facilitator` may now be passed
`--own-manifest-base-url`. If present, the batch signing and packet
encryption public keys in the relevant specific manifest will be checked
against the batch signing and packet encryption private keys provided to
`facilitator` by round tripping signature+verification or
encryption+decryption, respectively. If the keys do not match up,
`facilitator` aborts, enabling us to rapidly detect misconfigurations.
Closes #757
=> facilitator: crypto self-check at startup

deploy-tool/main.go, deploy-tool/main_test.go, manifest-updater/manifest/writer.go
In an effort to make this a bit easier to review, commit 171bbdd contains just the bugfix, and then 3d283eb has some refactoring to make this testable.
Resolves #756
=>  `deploy-tool`: don't generate packet encryption key twice #756 

facilitator/Cargo.lock, facilitator/Cargo.toml, facilitator/src/aws_credentials.rs, facilitator/src/bin/facilitator.rs, facilitator/src/config.rs, facilitator/src/gcp_oauth.rs
As we work towards #543, we need efficient `std::clone::Clone`
implementations on our `Transport` and `TaskQueue` implementations so
they can be efficiently shared across tasks. This commit starts towards
that goal by making the GCP and AWS credential providers `Clone`.
`aws_credentials::Provider` was already `Clone`, mostly thanks to
Rusoto's underlying implementations, but
`gcp_oauth::GcpOauthTokenProvider` needed some rework to implement
threadsafe interior mutability. I also took the opportunity to add some
test coverage.
This commit consists mainly of changes cherry-picked from #486.
=> facilitator: implement `Clone` on creds providers

.github/workflows/ci-build.yml, .github/workflows/deploy-tool-build.yml
Changes `on.pull_request.branches` so that PRs targeting branches
besides `[main, release/**]` will trigger CI, enabling automated tests
on stacked PRs.
=> actions: enable tests on all pull requests

facilitator/src/aws_credentials.rs, facilitator/src/bin/facilitator.rs, facilitator/src/config.rs, facilitator/src/gcp_oauth.rs, facilitator/src/manifest.rs, facilitator/src/task/pubsub.rs, facilitator/src/transport/gcs.rs
This commit enhances the existing `config::Identity` type to make it
into a struct wrapping an `Option<String>`. The goal is to abstract away
the special handling of the value `Some("")` as being equivalent to
`None` and make it easier to use `Identity` throughout the crate instead
of passing AWS role ARNs and GCP service account emails as
`Option<&str>` or `Option<String>` in various places. This will make
things more clear when a subsequent commit introduces support for AWS
authentication flows that first require authenticating to GCP, and so
`aws_credentials::Provider` will have to manage more than one identity.
We provide `std::str::FromStr` and `serde::Deserialize` implementations
on `config::Identity` to allow for graceful instantiation of `Identity`
from program arguments or JSON …
=> facilitator: beef up config::Identity type

facilitator/src/aws_credentials.rs, facilitator/src/bin/facilitator.rs, facilitator/src/config.rs, facilitator/src/gcp_oauth.rs, facilitator/src/http.rs, facilitator/src/task/pubsub.rs, facilitator/src/transport/gcs.rs, terraform/modules/data_share_processor/data_share_processor.tf, workflow-manager/aws/aws.go
`facilitator` was already capable of assuming AWS IAM roles when running
in GKE using `sts:AssumeRoleWithWebIdentity`, but it required that the
GCP SA mapped to the `facilitator`'s Kubernetes service account be
permitted to assume the role. This change enables `facilitator` to be
configured with an AWS IAM role to assume _and_ a GCP service account to
impersonate to do it. `facilitator` will get an _access_ token for the
default GCP service account, then use that to obtain an _identity_ token
for the specified GCP SA, then finally use that in a request to
`sts:AssumeRoleWithWebIdentity`.
On the way there, we do some cleanup in `gcp_oauth.rs` to clearly
distinguish between code that handles access tokens and code that
handles OpenID Connect identity/ID tokens, as previously all of these …
=> facilitator: use GCP SA to assume IAM role

facilitator/src/bin/facilitator.rs, facilitator/src/task.rs, facilitator/src/task/pubsub.rs, facilitator/src/task/sqs.rs
Due to recent advances in the science of credential obtention, we no
longer need methods on `TaskQueue` implementations to take `&mut self`.
This commit updates various method signatures to take immutable
references and fixes up the call sites.
=> facilitator: TaskQueue doesn't need &mut self

facilitator/src/bin/facilitator.rs, facilitator/src/config.rs, facilitator/src/http.rs, facilitator/src/lib.rs, facilitator/src/manifest.rs, facilitator/src/task/pubsub.rs, facilitator/src/task/sqs.rs
- Fix handling of `task-queue-identity` and a couple other `-identity` parameters
- The crypto self check will now gracefully be skipped if the instance's specific manifest does not exist, on the assumption that keys have not yet been generated and hence cannot be verified.
- Consult peer specific manifest to get identity to assume when writing to peer validation bucket as well as `peer-identity`
Resolves #833, #834
=> facilitator: bug fixes for international deployment

facilitator/src/batch.rs, facilitator/src/bin/facilitator.rs, facilitator/src/gcp_oauth.rs, facilitator/src/intake.rs, facilitator/src/logging.rs, facilitator/src/manifest.rs, facilitator/src/transport/gcs.rs, facilitator/tests/integration_tests.rs
We configure log level via the `RUST_LOG` environment variable. We were
using the `option_env!` macro to get its value, but that macro gets
environment variables at _compile_ time, not _run_ time, so it was
effectively impossible to set the log level to anything but `INFO`,
except by recompiling `facilitator`. We now use `std::env::var`, and
also apply `str::to_uppercase` to the value so that either of `debug` or
`DEBUG` will enable debug level logs.
=> facilitator: fix `RUST_LOG` handling

facilitator/Dockerfile
This commit restores some of the changes from #737 in order to emit
smaller container images.
- build `facilitator` with release profile
- build binary in a builder container based on `rust:alpine`, then ship
a smaller image based on `alpine` containing just the statically
linked binary
We can't remove the OpenSSL dependency until kube-rs/kube-rs/597 is
released, but this change takes our image size down to ~30 MB from >2
GB.
Related to #451
=> facilitator: smaller container image

terraform/state-surgery/README.md, terraform/state-surgery/state-surgery.sh
Adds a script, documentation and effectively a roll plan for migrating
`prod-us` (and any other existing `prio-server` environments) to the new
Terraform modules.
Part of #850
=> terraform: script and guide for state surgery

terraform/main.tf
Terraform insists that both sides of a conditional have the same type,
which was causing TF to coerce the numeric `aws-account-id` value into a
string, leading to malformed global manifests. We lower the `jsonencode`
function call into either side of the ternary operator to avoid this
coercion.
=> terraform: avoid TF type coercions

terraform/main.tf, terraform/variables/prod-us.tfvars, terraform/variables/staging-facil.tfvars, terraform/variables/staging-intl.tfvars, terraform/variables/staging-pha.tfvars
This series of commits makes use of [optional object fields](https://www.terraform.io/docs/language/expressions/type-constraints.html#experimental-optional-object-type-attributes) so that peer server manifest URLs and aggregation period parameters can optionally be set per-locality, defaulting to environment-wide variables set in tfvars. This allows us to have individual localities behave differently (e.g., the `ta-ta` locality in `prod-us` which uses different parameters than other localities) without repetitive config blocks in tfvars files.
Resolves #789
=> terraform: use optionals in per-locality config

terraform/variables/staging-intl.tfvars
Following discussion in the 2021/08/11 international ENPA sync, we are
configuring the staging-intl environment to send sum parts to the
staging MITRE portal server instance. We also take the opportunity to
deploy the latest `prio-facilitator` and `prio-workflow-manager` images
into that environment.
=> terraform: configure staging-intl for MITRE server

terraform/README.md, terraform/variables/prod-intl.tfvars
Adds a Terraform variables file for the `prod-intl` environment. No
localities are configured yet, but this is enough for `make
apply-bootstrap`.
=> bootstrap prod-intl environment

facilitator/Cargo.toml, facilitator/src/aws_credentials.rs
With some targeted use of `#[cfg(test)]`, we can omit
`aws_credentials::Provider::Mock` from the binary target of
`facilitator`, since it is only actually used in test targets. This
reduces binary size in the `release` configuration by 58,600 bytes
(`facilitator` is 27233040 bytes before, 27174440 after).
=> facilitator: move `rusoto-mock` to dev-dependency

terraform/variables/prod-intl.tfvars
@hostirosti let us know yesterday where the manifests for the
production instance of their data share processor would be, so this
commit updates the `prod-intl` TF vars accordingly. This change doesn't
do anything because we don't yet have any localities defined, and as
such does not need to be deployed.
=> update prod-intl with peer DSP manifest URL

deploy-tool/main.go, manifest-updater/manifest/storage.go
This was broken at some point in the past, and likely wasn't caught
before now only because no one has tried to create a new environment.
=> deploy-tool: reallow creation of singleton-ingestor manifests.

terraform/Makefile, terraform/variables/staging-facil.tfvars, terraform/variables/staging-intl.tfvars, terraform/variables/staging-pha.tfvars
* Move "custom metric" setup into the apply-bootstrap phase. This is
required because the AWS metric config depends on the CRD in the
custom metrics module, but this dependency isn't expressed in
terraform.
* Update staging variable files to use the latest version.
=> Updates based on Staging release.

deploy-tool/main.go
We pull these variables out here to avoid a common race described at
https://github.com/golang/go/wiki/CommonMistakes#using-reference-to-loop-iterator-variable
. This was found with `gosec` and triggered its G601 error.
=> Avoid a common race, fix gosec G601 errors

deploy-operator/controllers/suite_test.go
This fixes staticcheck SA1019 because zap has deprecated the other
method call.
=> use not-deprecated zap APIs

.github/workflows/ci-build.yml
A recent release of crate `tera` [breaks builds of
`grcov`](https://github.com/Keats/tera/issues/689). Until [`grcov` takes
a change to adopt the new
`tera`](https://github.com/mozilla/grcov/pull/697), we can work around
it by pinning the crate versions from the lockfile when installing
`grcov`.
=> GH actions: work around `grcov` build break

facilitator/rust-toolchain.toml
[`rust-toolchain.toml`](https://rust-lang.github.io/rustup/concepts/components.html)
allows us to pin a Rust toolchain version, guaranteeing that we are
using a compiler that supports recent language features we need (for
instance we might adopt the 2021 edition soon) or security fixes like
[CVE-2021-42574](https://blog.rust-lang.org/2021/11/01/cve-2021-42574.html).
=> facilitator: add `rust-toolchain.toml`

manifest-updater/secrets/types_test.go
After updating to the very latest golangci-lint, this error cropped up.
=> correct error usage in manifest-tests

terraform/variables/prod-intl.tfvars
Adds four Mexican states to `prod-intl` deployment.
=> terraform: deploy prod-intl/mx-{coa,jal,yuc,pue}

terraform/variables/prod-intl.tfvars
Our deploy of the four Mexican states got stuck because we ran out of
cores onto which to schedule pods, so we bump the max size of the node
group to 6. Further, we learned today that EKS doesn't automatically
deploy a cluster autoscaler for you (#1091), so we force the cluster to
six nodes.
=> prod-intl: force node group to 6 nodes

key-rotator/key/key.go, key-rotator/key/key_test.go, key-rotator/key/material.go, key-rotator/key/material_test.go, key-rotator/manifest/manifest.go, key-rotator/manifest/manifest_test.go
Making key.Key immutable will allow me to add validations/invariants later, e.g. "a non-empty key must have exactly one primary version."
key.Material is a more commonly-seen name than key.Raw for "a bunch of secret bytes you feed to an algorithm created by a cryptographer". See e.g. https://crypto.stackexchange.com/questions/80540/meaning-of-the-term-key-material.
=> Make key.Key immutable, rename key.Raw to key.Material.

key-rotator/manifest/manifest.go, key-rotator/manifest/manifest_test.go
Specifically (from https://github.com/abetterinternet/prio-server/issues/24):
* When being used to update keys in a manifest, keys must have at least one version.
* Post-update, manifests must have exactly one packet encryption key version.
* Post-update, manifests must have at least one batch signing key version.
* Post-update, manifests' non-key data must match the pre-update manifest data exactly.
* Post-update, manifests' key data for key versions that exist both pre- & post-update must match exactly.
This PR does **not** implement one final check from https://github.com/abetterinternet/prio-server/issues/24: "When being used to update keys in a manifest, existing key versions' public portions should match with the public keys written to the manifest, matching by creation time/key ID …
=> Add validations to manifest's UpdateKeys function

key-rotator/key/material.go, key-rotator/key/material_test.go, key-rotator/key/test/material.go, key-rotator/main_test.go, key-rotator/manifest/manifest.go, key-rotator/manifest/manifest_test.go
Specifically (from https://github.com/abetterinternet/prio-server/issues/24):
* When being used to update keys in a manifest, existing key versions' public portions should match with the public keys written to the manifest, matching by creation time/key ID (both of which would provide the same matching).
* Detection for: "if a batch signing key got so far ahead of its related manifests that the primary key was not included in the manifest, we would be trying to sign data with a key that we do not recognize as valid for verification."
* Detection for: "if a packet encryption key got so far ahead of its related manifests that the key did not include the version advertised as primary in the manifest, we would be asking clients to encrypt with a key we no longer consider valid for …
=> Add further validations to manifest's UpdateKeys function

terraform/variables/prod-intl.tfvars
(no rush on review, just keeping our committed config in line with what's actually deployed to production)
=> prod-intl: bump Kubernetes cluster from 6 -> 9 nodes.

key-rotator/key/material.go, key-rotator/storage/key.go, key-rotator/storage/key_test.go
Previously, we weren't checking the number of bytes returned from
`Decode`; in practice, this meant packet encryption keys that
round-tripped through serialization would end up with a `D` value that
was a few bytes too long. This didn't actually break anything for the
key rotator itself, since it doesn't use the key, but as one might
imagine the facilitator was none-too-happy about receiving these
malformed keys.
Sadly, this wasn't caught by tests... because the test that would have
caught it was set up to use a "bad" key. :cry:
=> Key rotator: fix bug with packet encryption key deserialization.

terraform/main.tf, terraform/modules/kubernetes/kubernetes.tf, terraform/modules/kubernetes_locality/kubernetes_locality.tf
Also, fixup a few small issues:
* Fix secret definitions so they don't try to modify _any_ secret
data, rather than only leaving secret data at "secret_key" alone.
(this is necessary because the new key rotation infra will also set
the "key_versions" secret data)
* Tweak key rotator AWS permissions to actually grant the necessary
permissions on the Manifest bucket's objects.
Stacked on https://github.com/abetterinternet/prio-server/pull/1138.
=> Key Rotator: terraform to allow controlling which localities have their keys rotated

workflow-manager/batchpath/batchpath.go
This fixes an issue found by the "lgtm.com" continuous security analysis: https://lgtm.com/projects/g/abetterinternet/prio-server/?mode=list. Noticed by Amir.
(For some date components like "month" or "day", the logical lower bound is actually 1 rather than 0. Looking to the code, this would be "normalized" against other date components, which might lead to a somewhat unexpected date output, but not to e.g. a crash or a panic.)
=> Workflow manager: bounds-check date components.

.github/workflows/push-docker-image-main.yml, .github/workflows/push-docker-image-release.yml
Pushing `prio-key-rotator` container images from a step separate from
the build doesn't work because the build cache gets cleaned up between
GH action steps, and so the built image is not visible to the push
steps. We could be clever about exporting the build image, but it's
easier to just push to dockerhub from the `build` step.
=> GH actions: push `key-rotator` from build step

key-rotator/manifest/manifest.go, key-rotator/manifest/manifest_test.go
This field is evidently not respected by any parties in the current ENPA
deployment (most/all of the expiration dates in the production
deployment are now in the past). But per discussion with ENPA team
members, we want to continue populating this with *something* in case
one of the parties is parsing this value & then ignoring it.
I also switch to specifying the dates as RFC 3339 rather than ISO 8601.
The populated data may very well fit both specs, but our current tooling
writes in RFC3339 format, so update the comment to be sure:
https://github.com/abetterinternet/prio-server/blob/f8e9707bb94471e6d9d7abcb9afda3216e652adc/deploy-tool/main.go#L186-L195
=> Add (bogus) expiry date to manifests' batch signing public key.

key-rotator/key/key.go, key-rotator/key/key_test.go, key-rotator/main.go
I think this is useful for debugging/observability. (I plan to add
similar functionality to manifests in an upcoming PR.)
=> Key rotator: add Key.Diff, use it to describe why we are writing keys.

facilitator/src/bin/facilitator.rs, terraform/modules/fake_server_resources/fake_server_resources.tf, terraform/modules/kubernetes/kubernetes.tf
This allows a poor man's version of config reloads, since the
newly-started pod will pick up any configuration changes (config map,
manifest contents, secret contents...).
=> Facilitator: allow workers to self-terminate after working too long.

facilitator/src/bin/facilitator.rs, key-rotator/storage/key.go, key-rotator/storage/key_test.go, terraform/modules/kubernetes/kubernetes.tf
Previously, the facilitator would always write the key identifier for
the "original" (e.g. old-style) key. This commit creates the necessary
plumbing for the correct key identifier to make it into the facilitator,
while still allowing fallback for "old-style" keys that have not yet
been rotated.
I'm still experimenting with/testing this, but I think it's ready for
review.
=> Use correct key ID for batch signing private key.

key-rotator/main.go, key-rotator/main_test.go
Normally, we only write keys to storage if we detect that they have
actually changed, e.g. the rotation policy caused a new key version to
be created, a new primary version to be elected, etc. Being able to
force a write even when there are no changes would be useful in some
circumstances, e.g. to force a backup, or a re-serialization of existing
keys.
=> Key rotator: add flags to force writing keys back to storage.

terraform/main.tf, terraform/modules/kubernetes_locality/kubernetes_locality.tf, terraform/variables/staging-facil.tfvars
I set it up at a rapid pace: the rotator runs once per ten minutes
rather than once per day, and will allow a new batch signing key version
to become primary after 6 hours rather than a week.
Haven't applied yet, but similar changes work for my dev environment. Will apply once this passes review.
=> Enable key rotator in staging-facil environment.

deploy-tool/main.go, key-rotator/key/material.go, key-rotator/storage/key.go, key-rotator/storage/key_test.go
Previously, they might be serialized as less than 32 bytes if the most-significant bytes of the key turned out to be zero. This would cause problems, AFAICT, in both key-rotator parsing logic as well as facilitator key-handling logic.
=> Update handling of serialized private key values.

facilitator/src/aws_credentials.rs, facilitator/src/bin/facilitator.rs, facilitator/src/config.rs, facilitator/src/gcp_oauth.rs, facilitator/src/lib.rs, facilitator/src/task/pubsub.rs, facilitator/src/transport/gcs.rs
This series of commits introduces factories for AWS and GCP credentials providers, allowing instances of `aws_credentials::Provider` and `gcp_oauth::GcpAccessTokenProvider` to be efficiently shared across task queues, transports and even each other.
Resolves #543
=> facilitator: cache credentials

workflow-manager/storage/storage.go
`workflow-manager` logs about enumerating bucket contents at level
`INFO`, which is chattier than necessary. Move a couple of log
statements up to `DEBUG`.
=> workflow-manager: log cloud storage reads at DEBUG

terraform/variables/staging-facil.tfvars
This enables key rotation. Already deployed; this PR brings the committed configuration state in line with what's deployed.
=> Staging-facil: bump container versions `0.6.18` -> `0.6.19`.

terraform/modules/account_mapping/account_mapping.tf, terraform/modules/eks/cluster_autoscaler.tf, terraform/modules/eks/eks.tf
In order to autoscale an EKS cluster (i.e., the worker nodes), one must
configure and deploy a `cluster-autoscaler` deployment. This commit does
that in Terraform, adapting the instructions from Amazon[1].
[1]: https://docs.aws.amazon.com/eks/latest/userguide/autoscaling.html#cluster-autoscaler
=> terraform: configure cluster-autoscaler in EKS

terraform/variables/staging-facil.tfvars, terraform/variables/staging-intl.tfvars, terraform/variables/staging-pha.tfvars
Sets min and max worker counts in staging environments to enable
horizontal pod autoscaling in those environments.
Part of #1169
=> terraform: configure pod autoscaling in staging

terraform/main.tf, terraform/modules/monitoring/monitoring.tf, terraform/variables/prod-intl.tfvars, terraform/variables/prod-us.tfvars, terraform/variables/staging-facil.tfvars, terraform/variables/staging-intl.tfvars
Adds support for plumbing Helm chart versions for Grafana, Prometheus
and the Stackdriver (GCP) and Cloudwatch (AWS) metrics exporters from
.tfvars into `monitoring.tf`. This commit only updates the versions in
staging environments. Once we observe that this is stable, a later PR
will update prod.
Part of #1196
=> terraform: update Grafana, Prometheus, exporters

terraform/modules/monitoring/prometheus_alerting_rules.yml
We now alert if there is there is less than 30% free space on the
persistent disk used by Prometheus to store metrics.
Resolves #364
=> terraform: configure alert for prometheus disk

terraform/variables/prod-us.tfvars, terraform/variables/staging-facil.tfvars
This will trigger a Packet Encryption Key rotation with the next daily run of the Key Rotator.
The diff looks acceptable (though it's so long it managed to fill the scrollback buffer, but all the localities are roughly the same). If https://github.com/abetterinternet/prio-server/pull/1201 makes it in quickly, I'll update this PR to include it.
=> prod-us: deploy key-rotator to `ta-ta` (integration test) environment.

key-rotator/main.go, key-rotator/storage/manifest.go, key-rotator/storage/manifest_test.go, terraform/main.tf, terraform/modules/kubernetes_locality/kubernetes_locality.tf
This change allows the `key-rotator` to automatically handle provisioning new keys, without the need for an operator to manually run `deploy-tool`. Once this is deployed to production, I think we can delete `deploy-tool` entirely.
The main change in this PR is to wire the `key-rotator` to have "manifest templates" so that it knows all the right non-key data to include in a new manifest, and update the logic to use the templates if no manifest has been written to the appropriate cloud storage bucket.
I also had to make a small change to key-rotation: we decided to disable rotation of the BSK, but we still need to "rotate" the initial empty key to provision a first version for new localities. I think this is small enough to sneak into this PR.
Other than unit tests, I deployed a new …
=> Key rotator: allow automatic turnup of new localities.

avro-schema/validation-batch.avsc, facilitator/Cargo.lock, facilitator/Cargo.toml, facilitator/src/batch.rs, facilitator/src/idl.rs, facilitator/src/lib.rs
`PrioValidityBatch` is comprised of a `PrioBatchSignature`, a `PrioValidityHeader`, and a sequence of `PrioValidityPacket`s (i.e. the three messages comprising a validation batch). The latter two messages are included as serialized bytes to allow signature verification, and then hash integrity checking, to be done over the same bytes that the signature/hash was generated against.
I also added some read tests that attempt to read "golden" serialized data and match it against what we expect it to deserialize to; this is to protect against the possibility of accidentally-backwards-incompatible changes (i.e. protecting against a change that still allows roundtripping through serialization/deserialization, but does not allow deserialization of data serialized with a previous version of the …
=> Facilitator: add `PrioValidityBatch` message with serialization support

docs/debugging.md, terraform/modules/gke/network.tf
Configures firewall rules to allow SSH to GKE worker nodes. I don't yet know how to do this for EKS. Second commit adds a document with basic instructions on SSHing into GKE nodes as well as obtaining and symbolicating `facilitator` coredumps.
=> GKE `facilitator` debugging

facilitator/src/bin/facilitator.rs, terraform/modules/kubernetes/kubernetes.tf
The previous configmap-based indirection would not trigger a job restart
on configmap change. This has led to a few instances (in preproduction
environments, thankfully) where the operator believed the facilitator
was running with different config than it was actually running.
Instead, now we specify flags directly in the deployment. This will
trigger terraform to cause an update whenever the configuration changes.
This also happens to cause the facilitator to log its config (at least, the
parts that were moved to flags), since it already logs its arguments on
startup.
Tested: this is running in my dev environment; jobs came up without complaint.
=> Specify flags for facilitator-based jobs directly.

facilitator/src/aggregation.rs, facilitator/src/idl.rs, facilitator/src/intake.rs, facilitator/src/lib.rs
Previously, if we received an undecryptable packet, we would fail out
the entire aggregation. Now, we silently skip ingestion batches that
contain undecryptable packets; our peer will also skip such ingestion
batches because we won't have generated a peer validation batch.
This avoids the unfortunate scenario of a single bad client packet
causing an entire aggregation batch to be dropped; instead, effectively
only the ingestion batch is dropped. This restores the behavior from
before we stopped writing own-validation batches.
=> During aggregation, skip batches with undecryptable data share packets.

facilitator/src/batch.rs
This is a backwards-compatible change, and the last change required to
allow Prio servers to *read* single-object batches.
Note that we now read all objects before performing validation; I think
this is OK since we don't do any parsing until validation is complete
(as before).
Testing: existing testing is based on round-tripping batches. For now, those tests serve to validate that the new BatchReader can read batches written by the existing BatchWriter. Once single-object-batch writing support exists, I will extend the tests to roundtrip single-object & multi-object batches.
Stacked on https://github.com/abetterinternet/prio-server/pull/1248.
=> Support reading batches with header/packet bytes in signature.

terraform/main.tf, terraform/modules/kubernetes/kubernetes.tf
The `kubernetes_manifest` resource in provider `hashicorp/kubernetes`
has a known issue[1] where resources created in a manifest can't depend
on other resources that don't exist yet. To work around this, we instead
use `gavinbunney/kubectl`'s `kubectl_manifest` resource, which does not
have this problem because it uses a different mechanism for planning.
[1] https://github.com/hashicorp/terraform-provider-kubernetes/issues/1380
Resolves #1088
=> terraform: use `kubectl_manifest`

workflow-manager/batchpath/batchpath.go, workflow-manager/main.go
I think this is safe for both new-style (single-object) & old-style
(multi-object) batches. Single-object batches are safe because they
really are just a single object, so checking for that one object is the
correct thing to do. Multi-object batches are safe because the signature
object was always written last (& only if writing the header & packet
objects succeeded), and both AWS & GCP offer strong read-after-write &
list consistency [1][2], so if the signature object was written we know
the batch & packet objects will also be written.
[1] https://docs.aws.amazon.com/AmazonS3/latest/userguide/Welcome.html#ConsistencyModel
[2] https://cloud.google.com/storage/docs/consistency
=> Workflow manager: consider batch complete if signature exists.

workflow-manager/main_test.go
This provides a test that is more realistic to how production is
configured (production also uses partially-overlapping
intake/aggregation windows), and would have caught the bug leading to
the 2021-10-26 postmortem.
Closes #1107.
=> Workflow manager: use partially-overlapping intake/aggregation windows for aggregation scheduling test.

terraform/main.tf, terraform/modules/data_share_processor/data_share_processor.tf, terraform/modules/kubernetes/kubernetes.tf
Defaults to disabled (as needed currently, until all production
deployments are released to a recent-enough version to be able to parse
single-object validation batches).
=> Terraform: config to allow single-object validation batches to be used.

terraform/Makefile
Historically, we blow away `.terraform` (or
`cluster_bootstrap/.terraform`, depending on which `prep` target is
invoked) before initializing `terraform`. The idea is to avoid the risk
of one environment's `.tfstate` bleeding into another, which `terraform
init` can sometimes sneakily do to you.
While working on #1274, I found myself switching between remote and
local Terraform backends a lot. My implementation plans had a lot of `rm
-rf .terraform` in them, in accordance with the `prep` and
`prep-cluster-bootstrap` targets in `terraform/Makefile`. The downside
of destroying the entire directory is that you have to reinstall the
Terraform providers every time you `plan` or `apply`. I learned that
what's really important is the file `.terraform/terraform.tfstate`, and
that if we destroy …
=> terraform: speed up prep targets in Makefile

facilitator/Cargo.toml, facilitator/src/bin/facilitator.rs, facilitator/src/gcp_oauth.rs, facilitator/src/logging.rs
These changes:
- capture `log` and `trace` output from dependencies
- add debug logging around lock management in module `gcp_oauth`
See individual commits for details. Note that having both a global `slog` logger and a `tracing` subscriber isn't ideal. I think the right thing to do would be to use `tracing` everywhere, and configure forwarding of `log` messages into a `tracing` subscriber. But this is the smallest change we can make that achieves what we need to now.
=> `facilitator` logging improvements

docs/debugging.md
Adds better instructions on using `ctr` to locate the conatiner
corresponding to the pod you want to debug, as well as instructions on
finding the *child* process of the `runc` shim.
Thanks to @hostirosti for the excellent feedback.
Resolves #1266
=> docs: fix `facilitator` debugging information

.github/workflows/ci-build.yml, terraform/Makefile, terraform/cluster_bootstrap/main.tf, terraform/main.tf
Adopts the latest release of `terraform`, 1.1.
- Since v0.15, `-lock` and `-verify-plugins` don't do anything in
`terraform init`
- bump `required_version` in `main.tf`
Part of #784
=> terraform: adopt `terraform` 1.1

key-rotator/main.go, key-rotator/manifest/manifest.go, key-rotator/manifest/manifest_test.go
These are unsafe to use in general--the pre-update validations serve as
a check that the key-rotator is running against a consistent set of
(manifest, k8s secret), the post-update validations serve as a check
that our update logic didn't do something very unexpected. But they may
be necessary if the key-rotator needs to run to fix an environment that
is already out-of-sync (and therefore triggering validation failures).
=> Key rotator: add flags to skip manifest pre/post-update validations.

facilitator/Cargo.lock, facilitator/Cargo.toml, facilitator/src/sample.rs
The UUID is itself random, so sample data is still random; the upside of
this is that we can now determine a given sample ingestion packet's data
without reading & decrypting the data shares. This will be handy for a
validator which wants to make sure the sums we are emitting match up
with the ingestion packets included in those sums.
[Note that since even "random" v4 UUIDs contain a few deterministic
bytes, part of the data will be deterministic; I think that's OK.]
=> Generate sample data deterministically from packet UUID.

facilitator/src/bin/facilitator.rs, facilitator/src/intake.rs, facilitator/src/sample.rs, facilitator/tests/integration_tests.rs
This function produces the expected sum from a SumPart comprised of the
given batch UUIDs. This turned out to be a lot simpler than I expected:
I didn't need to read the validation batches in the sum part to get
their UUIDs because the validation batch uses the same UUID as the
ingestion UUID (and the ingestion UUID is what determines the data
included in the ingestion batch, along with the "static"
dimension/packet_count parameters).
The test is a "weak" test in that it only tests that the result of
expected_sample_sum_for_batches matches up with the sum of a few
repeated calls to generate_ingestion_sample -- it does not test the full
intake -> ingest -> aggregate flow from end-to-end. The goal of this
test is to make sure these two functions agree on the sums they believe
they are …
=> Add expected_sample_sum_for_batches.

facilitator/src/manifest.rs
I call the new version "V1or2" -- naming assistance very welcome.
AFAICT, the only difference between the two versions it that V2 added an
optional "peer_validation_identity" field which defaulted to None.
Generic code that attempted to extract a peer_validation_identity from a
V1 manifest would get None, as well. Since this isn't a
backwards-incompatible change, we might as well simplify things by going
back to only a single version.
This simplifies #659 in that we will no longer need to represent both
DSP manifest formats for testing since there is now only a single
manifest format.
=> Coalesce DSP-specific manifests versions 1 & 2 into a single version.

facilitator/rust-toolchain.toml, facilitator/src/aws_credentials.rs, facilitator/src/bin/facilitator.rs, facilitator/src/task.rs, facilitator/src/transport/gcs.rs
Previously, after the first time we extended a task's deadline, we would
attempt to extend the deadline again every time we checked if the
deadline should be updated. Now, every time we extend a task's deadline,
we "reset" the starting point so that we only attempt to reset the
deadline again once enough time has passed.
I had to switch to "stable" channel to get a version of Rust (1.58) recent enough to have const duration-handling functions.
Closes #319.
=> Fix bug around task-deadline extension.

terraform/cluster_bootstrap/modules/gke/gke.tf
@hostirosti pointed out a recent GKE feature that lets us opt into
spot VMs in our GKE cluster. Much like AWS spot instances, spot VMs are
drawn from spare Google Compute Engine capacity and cost a lot less, in
exchange for lesser availability, which is acceptable for a batch
processing system like ours.
https://cloud.google.com/kubernetes-engine/docs/concepts/spot-vms
=> terraform: opt into spot VMs on GKE

facilitator/src/manifest.rs
This enforces that the two versions can actually be expressed as one
version. Unlike the DSP global manifest, I believe there is no
equivalent validation to be written: the only difference between the two
versions was the addition of an optional field
(peer_validation_identity), so the two message versions are essentially
identical.
=> Re-remove version-based validation from DSP locality-specific manifest.

.github/dependabot.yml, terraform/main.tf
I noticed that #1346 reintroduces the `google-beta` provider into the main TF module, but we need to make sure its version is in sync with the regular Google one. Additionally, configures dependabot to manage provider versions in `cluster_bootstrap`.
=> Terraform fixes

terraform/cluster_bootstrap/main.tf, terraform/main.tf, terraform/variables/prod-intl.tfvars, terraform/variables/prod-us.tfvars, terraform/variables/staging-facil.tfvars, terraform/variables/staging-intl.tfvars, terraform/variables/staging-pha.tfvars
When this new variable is set, the `aws` provider will refuse to take any actions if it is given credentials to a mismatched account.
For now, I have added a commented-out declaration in each .tfvars file, with an example account ID, assuming we don't want to check in any actual account IDs.
=> terraform: Use aws provider's allowed_account_ids

workflow-manager/README.md
It looks like workflow-manager is no longer responsible for cleaning up old Kubernetes jobs, since `facilitator` became a deployment reading from queues.
=> workflow-manager: Update README, no more k8s jobs

terraform/Makefile, terraform/cluster_bootstrap/.terraform.lock.hcl, terraform/cluster_bootstrap/main.tf, terraform/cluster_bootstrap/modules/gke/gke.tf, terraform/main.tf
This builds on PR #1295. We want to be able to destroy and create infrastructure for development or staging purposes, but currently we always use the same KMS keyring name, and keyrings cannot be deleted. This will add a randomized component to our interpolated keyring names, while leaving any keyrings with old names untouched, and pass the keyring name/ID from the cluster_bootstrap stage to the next stage.
I'll follow up with Terraform plans from a clean run on my development environment in a comment.
=> Randomize KMS Keyring name

terraform/variables/prod-intl.tfvars, terraform/variables/prod-us.tfvars, terraform/variables/staging-intl.tfvars, terraform/variables/stg-us-pha.tfvars
Also specifies a machine type for VMs in the `stg-us-pha` env.
=> terraform: bring all envs to 0.6.24 containers

.github/dependabot.yml, key-rotator/Dockerfile, workflow-manager/Dockerfile
Also, update dependabot configuration to automatically update
key-rotator dependencies, and drop a few directories that no longer
exist.
=> Update key-rotator & workflow-manager to Go 1.17.7.

terraform/README.md, terraform/cluster_bootstrap/main.tf, terraform/cluster_bootstrap/modules/eks/eks.tf, terraform/main.tf, terraform/modules/eks/cluster_autoscaler.tf, terraform/modules/eks/eks.tf, terraform/variables/prod-intl.tfvars, terraform/variables/staging-intl.tfvars, terraform/variables/stg-us-pha.tfvars
Plumbs variables for versions of a few EKS cluster components into
environment .tfvars files so that we can perform upgrades via Terraform.
Specifically we configure:
- The version of the EKS cluster itself. The EKS cluster version is derived
from the upstream Kubernetes version. See [1] for details.
- The version of the AMI used on worker nodes. The EKS API can figure out an
appropriate AMI from the cluster Kubernetes version. The `aws` provider
documentation[2] suggests we could omit this but we explicitly set
the same version as the cluster, since the EKS documentation[3]
states that we have to update the node groups after updating the
cluster.
- The VPC CNI add-on version. We must pick a version that is
compatible with the cluster version, per EKS documentation[4].
- The cluster …
=> terraform: manage EKS cluster component versions

terraform/variables/staging-intl.tfvars, terraform/variables/stg-us-facil.tfvars, terraform/variables/stg-us-pha.tfvars
Deploys 0.6.25 containers to `stg-us-pha`, `stg-us-facil` and
`staging-intl`.
Part of #1373
=> terraform: deploy 0.6.25 containers to staging

facilitator/Cargo.lock, facilitator/Cargo.toml, facilitator/src/aws_credentials.rs, facilitator/src/retries.rs, facilitator/src/transport/s3.rs
Add a new wrapper type, RetryingProvider, and use it in the Provider enum. This also splits out latency metrics into another wrapper type, MeasuringProvider, for better separation of concerns. An async variant of retry_request() is added to support the RetryProvider.
I decided against wrapping the default provider in RetryingProvider, as it would only ever make network connections to the same machine, either via the instance metadata service or the container credentials service. I did swap out `DefaultCredentialsProvider` for `AutoRefreshingProvider<MeasuringProvider<ChainProvider>>`, so I could interpose latency measurement at the correct point, and not measure accesses to cached credentials.
Edit: fixes #1318
=> facilitator: retry upon failure of AWS cred. fetch

terraform/main.tf, terraform/modules/fake_server_resources/fake_server_resources.tf
This was due to main.tf's
data_share_processors_to_sum_part_writer_token_creator interfering with
the fake_server_resources.tf's
integration_test_identity_to_my_sum_part_bucket_writer_token_creator. I
fix this by specifying the membership in
data_share_processors_to_sum_part_writer_token_creator directly; the
downside is this "leaks" some integration-test configuration outside of
fake_server_resources.tf.
=> Fix flapping of fake-ingestor identity in sum-part-writer bucket.

facilitator/src/aws_credentials.rs
Returning a newly constructed std::fmt::Error from here is incorrect, as format implementations should only return errors through propagation. In particular, format!() will panic if it receives an error from this code.
=> facilitator: gracefully handle Err in fmt::Display

terraform/variables/stg-us-facil.tfvars, terraform/variables/stg-us-pha.tfvars
This has been enabled & working OK in my dev environment for around a
month now--now that staging is releasable again, I think it is wise to
test upcoming changes in staging rather than in dev-envs only.
I set things up such that the facil & PHA deployments match their
settings here.  This is not a requirement, but it does simplify testing.
I leave one locality using multiple-object validation batches, to ensure
we don't somehow break backwards-compatibility.
`make plan` for stg-us-facil:
<details>
<summary>Click to expand</summary>
```
Terraform will perform the following actions:
- resource "google_service_account_iam_binding" "data_share_processors_to_sum_part_bucket_writer_token_creator" {
- etag               = "BwXYBR2HsHI=" -> null
- id                 = …
```
=> Enable --write-single-object-validation-batches in staging.

facilitator/src/aggregation.rs, facilitator/src/batch.rs, facilitator/src/bin/facilitator.rs, facilitator/src/intake.rs, facilitator/src/lib.rs, facilitator/src/sample.rs
As a team, we decided that this lint added more noise than value.
I had to add the "top-level" annotation to both `facilitator.rs` & `lib.rs` -- I believe the `facilitator.rs` annotation covers lints for the binary (i.e. in `facilitator.rs` specifically), while `lib.rs` annotation covers the rest of the crate (i.e. the "library" portion).
=> Disable clippy::too_many_arguments lint.

terraform/variables/prod-intl.tfvars, terraform/variables/prod-us.tfvars
This also updates EKS cluster version in prod-intl. See #1373 for
details.
=> terraform: release 0.6.25 containers to prod-us

facilitator/src/aggregation.rs, facilitator/src/test_utils.rs, facilitator/tests/integration_tests.rs
If an ingestion batch contains a packet that cannot be decrypted, then
the intake task for it will fail, currently producing a dead letter.
However, we gracefully handle this case at aggregation time, because if
one batch out of `n` contains an undecryptable packet, we still want to
aggregate over the other `n - 1` batches. However, when discarding a
batch from the aggregate, we were still including its batch UUID in the
sum part message sent to the portal server, which causes our
aggregator's list of batch UUIDs to not match up with the peer's, which
the portal server rightfully considers an error.
This commit makes the aggregator only include a batch UUID if the
batch's packets were aggregated into the sum part.
Resolves #1414
=> facilitator: correctly report included batch UUIDs

facilitator/src/bin/facilitator.rs, facilitator/src/manifest.rs, facilitator/src/transport/local.rs
This fixes a new Clippy warning (stabilized with the release of rust 1.59), clippy::single_char_pattern, and test-only uses of a newly deprecated function, IntoIter::new() (also deprecated in rust 1.59).
(Note that the new Clippy warning would manifest as CI failures once GitHub updates their base images)
=> facilitator: fix warnings

facilitator/Cargo.lock, facilitator/Cargo.toml, facilitator/src/aggregation.rs, facilitator/src/aws_credentials.rs, facilitator/src/batch.rs, facilitator/src/bin/facilitator.rs, facilitator/src/config.rs, facilitator/src/gcp_oauth.rs, facilitator/src/http.rs, facilitator/src/idl.rs, facilitator/src/intake.rs, facilitator/src/lib.rs, facilitator/src/manifest.rs, facilitator/src/task.rs, facilitator/src/task/pubsub.rs, facilitator/src/task/sqs.rs, facilitator/src/transport.rs, facilitator/src/transport/gcs.rs, facilitator/src/transport/local.rs, facilitator/src/transport/s3.rs, terraform/modules/kubernetes/kubernetes.tf, terraform/modules/pubsub/pubsub.tf, terraform/modules/sns_sqs/sns_sqs.tf
This introduces enum-based error handling in the IDL module. It eliminates all but one use of anyhow in `src/idl.rs`, and effectively moves several variants of the crate-level `Error` to this module.
This doesn't introduce any behavior changes for packet decryption failures, etc. yet. I figured this module would be good to start with, as it has the highest density of `anyhow::Context::context()` calls. In the interest of eating an elephant one bite at a time, I'm putting this up for early feedback, and we can treat it as a draft if we like.
=> facilitator: structured error handling

facilitator/src/bin/facilitator.rs, terraform/modules/monitoring/prometheus_alerting_rules.yml
This fixes an issue with the expressions used for failure rate alerting. It also introduces a new value of "rejected" for the label "status", on the "tasks_finished" metrics, for tasks that result in a non-retryable error. We apply the "rejected" value when we divert the task to a separate rejected queue, rather than let it reach the dead letter queue. A new alert is introduced to monitor the fraction of tasks being rejected, and alert if it is too high.
~~Edit: deploy note - this will require deleting the secret monitoring/prometheus-alertmanager-config and running Terraform to re-populate it~~
=> Fix failure rate alerting, new alert for rejecting

facilitator/src/aggregation.rs, facilitator/src/idl.rs, facilitator/tests/integration_tests.rs
Previously, we didn't check, and would happily aggregate even if some of
the parameters didn't match--but at a higher level, data with different
parameters can't be meaningfully aggreagated, so this produced
non-useful output. All we can do is notice & complain, but we should do
so rather than producing bad output.
=> During aggregation, require ingestion header parameters to match.

terraform/cluster_bootstrap/.terraform.lock.hcl, terraform/cluster_bootstrap/main.tf, terraform/main.tf
This adds a data source to both Terraform main modules to shell out to git in order to record the checked out commit. The commit hash will be stored in the state, and I included it in an output from the module for convenience.
Sample output:
```diff
Changes to Outputs:
+ git-describe = "52972e5-dirty"
```
What do we think, is this worth having?
(Note that terraform/.terraform.lock.hcl already contains the `external` provider, as it is already used in `data_share_processor`, without inclusion in `required_providers`)
=> terraform: include status of working dir. in state

terraform/cluster_bootstrap/modules/eks/eks.tf, terraform/modules/eks/config/application-log.conf, terraform/modules/eks/config/dataplane-log.conf, terraform/modules/eks/config/host-log.conf
This fixes #1391. We can hold off on merging this until we want to deal with the manual Terraform migration required, (or combine it with other such changes) but I figured I may as well get it written up and tested.
This change will require importing the log group that EKS already created, to keep Terraform from trying to create it again and finding that its name is already in use. For example:
Run at least one makefile target to make sure that cluster_bootstrap/.terraform/terraform.tfstate points to the correct backend bucket for this environment.
`$ ENV=<environment name> make plan-cluster-bootstrap`
Import the log group resource. (The easiest way to get the log group's name is to attempt to apply once, and look at the log group name in the error message)
`$ ENV=<environment name> …
=> terraform: configure log retention period

terraform/variables/staging-intl.tfvars, terraform/variables/stg-us-facil.tfvars, terraform/variables/stg-us-pha.tfvars
Diff for stg-facil (it's just container version updates):
<details>
```
Terraform will perform the following actions:
~ resource "kubernetes_deployment" "integration-test-sample-generator" {
id               = "tester/integration-test-sample-generator-asgard-ingestor-1"
~ spec {
~ template {
~ spec {
~ container {
~ image                      = "letsencrypt/prio-facilitator:0.6.28" -> "letsencrypt/prio-facilitator:0.6.29"
name                       = "integration-test-sample-generator"
}
}
}
}
}
~ resource "kubernetes_deployment" "integration-test-sample-generator" {
id               = "tester/integration-test-sample-generator-asgard-ingestor-2"
~ spec {
~ template {
~ spec {
~ container {
~ image                      = "letsencrypt/prio-facilitator:0.6.28" -> …
```
=> Update staging to 0.6.29.

.github/workflows/ci-build.yml
This is follow-up to #1471 and #1480, to use go 1.18 in CI tests as well.
=> Bump go version in CI to 1.18

terraform/modules/eks/log.tf
The fluent-bit DaemonSet was previously running an old version of this image, which included Fluent Bit 1.6. That version did not support the `log_retention_days` configuration parameter for the `cloudwatch_logs` plugin, and thus it would fail to start. Upgrading the container brings the Fluent Bit version to 1.8, which does support this parameter.
=> terraform: Upgrade aws-for-fluent-bit container

terraform/Makefile
This fixes some issues with quoting of variables in the Makefile. The first commit fixes the input validation conditionals, which would have previously been comparing the empty string to `""`. The second commit avoids wrapping the path to the variables file in two sets of double quotes, for consistency.
=> Fix makefile quoting

terraform/modules/monitoring/prometheus_alerting_rules.yml
This adds two partly overlapping alerting rules using `kube-state-metrics` data. The first checks for containers that restart repeatedly, and the second checks for containers that are waiting for one reason for an extended period of time. These will catch `CrashLoopBackOff` and `ImagePullBackOff` conditions, as well as `restartPolicy: Always` containers that exit with a success code quickly.
=> Add alert rules for unhealthy containers

.github/dependabot.yml
This enables Dependabot on our GitHub Actions and a few Terraform modules that have their own `required_providers` block.
=> Enable dependabot on more directories

facilitator/src/aggregation.rs, facilitator/src/intake.rs, facilitator/src/transport.rs, facilitator/src/transport/gcs.rs, facilitator/src/transport/s3.rs, facilitator/tests/integration_tests.rs
This PR fixes three bugs uncovered by an unusual occurrence seen in production.
We see reports like this about once a week:
```
MX-YUC-APPLE: Files not summed
The following MX-YUC-APPLE files were not summed for some reason:
com.apple.EN.UserRiskParameters (1)
•    202203270000 - 202203270800
ISRG: total_ind_cli: 22743, batch UUID len: 1142
Google: total_ind_cli: 22743, batch UUID len: 1143
```
So this indicates that while both aggregators processed the same number of inputs (`total_ind-cli`), the Google aggregator reported having aggregated over one more batch. This has been observed before when one aggregator can't process a batch because it can't decrypt one or more ingestion packets in the batch, but in this case, Robert hadn't observed any decryption failures. What he did have were …
=> Bugfixes for empty ingestion batch handling

terraform/modules/monitoring/monitoring.tf, terraform/modules/monitoring/resource_usage_dashboard.json
This adds a second Grafana dashboard, which displays CPU and memory usage at the node level, as well as CPU and memory usage of containers beyond their resource requests. As this is a workload-independent dashboard, I plan to make use of it directly with Janus as well. See below for screenshots in AWS and GCP clusters.
=> Add Grafana dashboard to monitor resource usage

facilitator/src/aggregation.rs, facilitator/src/idl.rs
The 1.60.0 toolchain brings improvements to [`#[warn(clippy::ptr_arg)]`](https://rust-lang.github.io/rust-clippy/master/index.html#ptr_arg), for mutable pointers, and this emitted a warning on our codebase in two places.
=> Fix clippy lints

facilitator/Cargo.lock, facilitator/Cargo.toml, facilitator/src/bin/facilitator.rs, facilitator/tests/cmd/aggregate-worker.trycmd, facilitator/tests/cmd/aggregate.trycmd, facilitator/tests/cmd/generate-ingestion-sample-worker.trycmd, facilitator/tests/cmd/generate-ingestion-sample.trycmd, facilitator/tests/cmd/intake-batch-worker.trycmd, facilitator/tests/cmd/intake-batch.trycmd, facilitator/tests/cmd/lint-manifest.trycmd, facilitator/tests/cmd/main.trycmd, facilitator/tests/cmd/validate-ingestion-sample-worker.trycmd
This adds reference tests for the `--help` output of each subcommand. Such reference tests are the first recommended step in migrating to the next version of clap.
=> facilitator: command-line help reference tests

terraform/variables/prod-intl.tfvars, terraform/variables/prod-us.tfvars, terraform/variables/staging-intl.tfvars, terraform/variables/stg-us-facil.tfvars, terraform/variables/stg-us-pha.tfvars
This update includes a number of small chart changes, and a version update for its exporter container. The only breaking change concerns a value we do not set.
=> Update stackdriver-exporter Helm chart to 2.2.0

facilitator/Cargo.lock, facilitator/Cargo.toml, facilitator/src/transport/s3.rs
I also had to modify a few tests to manually create an HTTP connector
due to a breaking change to make HttpClient support HTTPS only by
default in
https://github.com/rusoto/rusoto/commit/df317924d260ef002a8596b303902eb8d9298e24.
=> Update Rusoto 0.47.0 -> 0.48.0.

terraform/modules/monitoring/http_api_dashboard.json, terraform/modules/monitoring/monitoring.tf
This adds a new Grafana dashboard showing request volumes to and error rates from HTTP API metrics. This cleans up and memorializes the queries I was looking at on Monday.
Here's a screenshot of the dashboard on prod-us. One strange artifact to be aware of: there is one service with a 50% error rate. This is due to us trying to fetch an ingestor global manifest, getting a 403, and falling back to fetch per-locality manifests.
=> Add dashboard with HTTP API metrics

facilitator/Cargo.lock
This pulls in a fix for RUSTSEC-2021-0023. `rand_core v0.6.1` was a transitive dependency of `elliptic-curve` and other crates, but we only used that crate for key parsing, not encryption or key generation.
=> Upgrade rand_core

.github/workflows/ci-build.yml
This introduces a number of new linters. I ran it locally and didn't find any issues.
=> Upgrade golangci-lint to v1.45.2

terraform/modules/monitoring/prometheus_alerting_rules.yml
This adds a new alerting rule to address #1609. The main constraint I had to design around was the spikiness of incoming data in Apple ingestion buckets. If this changes in the future, we could adjust this alerting rule to be both stricter and quicker-acting.
The two key calibration parameters are the averaging time period of 16 hours, and the relative alarming threshold at 0.25x of historical ingestion rate. I chose to average the rates over 16 hours because, over the last two weeks, the longest duration that any one locality went between bursts of packets was about 14 hours. Then, looking at those averaged rates, normal values fluctuated with a dynamic range of up to ~3.5x, so the relative threshold of 0.25x should avoid false alarms.
I tested this expression against historical data, …
=> Add alert for low packet ingestion rate

terraform/modules/kubernetes/kubernetes.tf
This change will delete and recreate our four HPAs in each namespace, to move off of the not-yet-deprecated `kubernetes_horizontal_pod_autoscaler`. Both the unversioned (before) and versioned (after) Terraform resources create resources with API version autoscaling/v2beta2. I also changed their name to avoid collisions while applying. This is a good-enough fix for #1629.
=> Versioned resources for HorizontalPodAutoscalers

terraform/main.tf, terraform/modules/data_share_processor/data_share_processor.tf, terraform/modules/fake_server_resources/fake_server_resources.tf
This allows setting a permissions boundary policy on all AWS IAM roles created in a non-pure GCP environment.
This is the first part of IN-7312; it will make writing and testing policies easier.
=> Add optional var for permissions boundary policy

terraform/cluster_bootstrap/modules/gke/gke.tf
This will keep us using "pd-standard" boot disks, even after the defaults for new node pools change. I checked the plans with this applied, and there was no diff, as the default value of "pd-standard" is already recorded in the state.
=> terraform: Explicitly specify 'standard' boot disk

terraform/modules/eks/log.tf
This upgrade includes a new feature to automatically refresh Kubernetes service account tokens, which is necessary in Kubernetes 1.21.
I have tested this on my cluster, and log collection still works fine. This will address the issue noted in the emails from AWS today. The relevant pods are 51 days old now, and tokens currently expire at 90 days, so we have plenty of time to resolve this. I propose merging this after the next production deploy, and picking it up in next week's deploys.
=> Upgrade to AWS for Fluent Bit 2.25.0

terraform/modules/monitoring/prometheus_alerting_rules.yml
The temporal distribution of reports from Apple ingest servers changed two days ago. There are still three peaks a day, but the peaks are broader, shorter, and arrive at different times. The gap between two peaks yesterday evening was significantly longer than seen previously. This change adjusts the low ingestion rate alert to adapt to the new behavior.
=> Recalibrate ingest_rate_low alert

facilitator/Cargo.toml, facilitator/src/metrics.rs, terraform/.terraform.lock.hcl, terraform/main.tf
This includes three small cleanups that came up while going over dependency updates.
1. `regex` can be a dev-dependency, as it is only used in tests.
2. There is a `const` in the Prometheus crate we can use for the text format media type.
3. `hashicorp/tls` is only used in the `cluster_bootstrap` module, but it was specified in both `main.tf` files.
=> Dependency and Prometheus Cleanups

terraform/modules/monitoring/prometheus_alerting_rules.yml
The metrics `facilitator_intake_tasks_finished` and `facilitator_aggregate_tasks_finished` do not have `kubernetes_namespace` or `kubernetes_name` labels with our current relabeling configuration.
=> terraform: fix Prometheus labels on task alerts

terraform/modules/monitoring/http_api_dashboard.json, terraform/modules/monitoring/prometheus_alerting_rules.yml, terraform/modules/monitoring/resource_usage_dashboard.json, terraform/variables/prod-intl.tfvars, terraform/variables/prod-us.tfvars, terraform/variables/staging-intl.tfvars, terraform/variables/stg-us-facil.tfvars, terraform/variables/stg-us-pha.tfvars
This upgrade includes a change to the "honor_labels" configuration of all scrape targets. This change affects certain Kubernetes-related label names, which are used in dashboards and alerts.
=> Upgrade Prometheus Helm chart

terraform/variables/prod-intl.tfvars, terraform/variables/prod-us.tfvars
The staging environments have been running well, I don't see any issues with Prometheus, Grafana, or custom metrics. The prod plans look as expected.
=> terraform: deploy 0.6.39 to production

key-rotator/go.mod, key-rotator/go.sum
Produced by `go get -u gopkg.in/yaml.v3`.
=> Update gopkg.in/yaml.v3 to version 3.0.1.

terraform/variables/prod-intl.tfvars, terraform/variables/prod-us.tfvars
As with staging, there are no changes to `cluster_bootstrap`, and the main stage's plans only show container image upgrades.
=> Update production to 0.6.41

terraform/variables/staging-intl.tfvars, terraform/variables/stg-us-facil.tfvars, terraform/variables/stg-us-pha.tfvars
The Terraform plans look as expected, based on the spot VM changes. Note that this includes changes to `cluster_bootstrap` as well.
=> Update staging to 0.6.44

terraform/modules/monitoring/prometheus_alerting_rules.yml, workflow-manager/main.go
Our workflow-manager heartbeat alert has been firing after a single failed workflow-manager run, because this code path registered the gauge `workflow_manager_last_success_seconds`, never set its value, and sent the default value of 0 to prometheus-gateway. This PR fixes this issue by only registering success/failure gauges immediately before setting their values. It also fixes the `workflow_manager_last_failure_seconds` metric by pushing metrics after the gauge has been updated, and before `os.Exit()` is called.
I'm posting this as a draft early while I work on testing it.
=> workflow-manager: Avoid writing 0 to time gauges

workflow-manager/storage/storage.go
This fixes #1832. It should cut down our requests to STS by at least an order of magnitude. I confirmed that the STS requests already benefit from the SDK's retry logic. Thus, I think this change should effectively eliminate the class of STS errors we have been seeing. (beyond recent metrics/alerting-only fixes)
I tested this out on my AWS development environment, and it sped up jobs from nine seconds to three seconds, so I expect we should see a nice wall clock benefit as well in production. (prod-us takes around one minute and prod-intl takes around six minutes currently)
=> workflow-manager: Store S3 client for reuse in later operations

terraform/modules/monitoring/prometheus_alerting_rules.yml
This adds a new alert based on kube-state-metrics data, to check for any pods that are stuck pending. This could happen if our resources are under-provisioned, or if there's an issue with the pod's affinities or taint tolerations, relative to the rest of the cluster.
Over the last week, we have seen an increased number of pods that are pending, but only for approximately one minute. This was introduced by #1703 and will be fixed by #1816. This alert's threshold is far higher, so it will only fire if there's a more serious issue, beyond our thundering herd of cron jobs.
=> Add an alert for pods that are pending too long

terraform/main.tf, terraform/modules/data_share_processor/data_share_processor.tf, terraform/modules/kubernetes/kubernetes.tf, terraform/modules/kubernetes_locality/kubernetes_locality.tf, terraform/modules/nfs_server/nfs_server.tf
This adds an option to set up an in-cluster NFS server, backed by a GCE Persistent Disk, and has workflow-manager and key-rotator jobs write out heap profiles to a volume backed by the NFS server. An NFS server is necessary because we need a ReadWriteMany persistent volume, and this is the simplest way to achieve that on GKE. (GCP has a managed NFS offering, but its minimum filesystem size is 1 TiB)
It is intended that this new option will be turned on for a brief time to collect profiles, the profiles will be copied out of the nfs-server pod for later analysis, and the option will be turned off again to tear down NFS-related infrastructure. The added NFS mounts are additional potential failure points for these jobs, so we may as well remove them in normal operation.
This is part of …
=> terraform: Add option to collect heap profiles

terraform/variables/prod-us.tfvars, terraform/variables/stg-us-facil.tfvars, terraform/variables/stg-us-pha.tfvars
Now that our GKE clusters have separate spot and standard node pools (in #1703), we can set `min_node_count=0` in GKE environments. (Previously, min_node_count had a different meaning for GKE, and controlled the number of standard VMs per zone) This will allow cluster-autoscaler to shut down up to three spot VMs, depending on workload volume. (I did the same in stg-us-pha as well)
=> Set min_node_count=0 in remaining environments

terraform/variables/prod-intl.tfvars, terraform/variables/prod-us.tfvars
The plans look as expected. prod-us will require `apply-cluster-bootstrap`. Both prod environments will require manual intervention to update the `prometheus-alertmanager-config` secret and re-insert the VictorOps API key.
=> Update production to 0.6.47

terraform/cluster_bootstrap/main.tf, terraform/cluster_bootstrap/modules/eks/eks.tf, terraform/main.tf, terraform/modules/eks/eks.tf, terraform/variables/prod-intl.tfvars, terraform/variables/staging-intl.tfvars, terraform/variables/stg-us-pha.tfvars
This sets up the EBS CSI addon, which will be required as of EKS version 1.23. It also configures the required IAM role for the addon, following the documentation. As of EKS version 1.23, the in-tree EBS plugin will be removed, and any StorageClass using ` kubernetes.io/aws-ebs` will be migrated to use this addon instead, automatically.
I tested this by creating a StorageClass with provisioner `ebs.csi.aws.com`, a PVC, and a pod, while watching the EBS CSI deployment's logs. The addon successfully created, mounted, unmounted, and deleted the volume.
Note that this change requires `make apply-cluster-bootstrap` to deploy.
=> Add EBS CSI addon

terraform/variables/staging-intl.tfvars, terraform/variables/stg-us-facil.tfvars, terraform/variables/stg-us-pha.tfvars
Aside from container image upgrades, the plans also include changes to `random_string` resources like the following.
```
~ resource "random_string" "account_id" {
id          = "doyinmbcikazosdn"
}
```
This is due to a change in the most recent version of the provider, "During upgrade state, ensure min_upper is populated".
=> Update staging to 0.6.53

facilitator/src/batch.rs
This fixes a warning that newly appears with a 1.64 Rust toolchain. The derive macro internally uses named arguments, so we were getting the following message.
```
warning: named argument `field__0` is not used by name
--> src/batch.rs:156:13
|
156 |       #[error("key identifier {0} not present in key map {:?}")]
|  _____________^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^__-
| |             |
| |             this named argument is referred to by position in formatting string
157 | |     UnknownKeyIdentifier(String, Vec<String>),
| |___- this formatting argument uses named argument `field__0` by position
|
= note: `#[warn(named_arguments_used_positionally)]` on by default
help: use the named argument by name to avoid ambiguity
|
157 | field__0  UnknownKeyIdentifier(String, …
```
=> Fix a clippy warning

.github/dependabot.yml
This raises the limits on open Dependabot PRs for Go, Cargo, and Terraform. Previously, each run was limited to five open PRs by default. As we only have Dependabot run weekly, we should raise this so it can open more PRs without manual intervention (i.e., navigating [here](https://github.com/divviup/prio-server/network/updates) and re-running it).
I noticed that we did hit the limit for Go this week, and I infer we probably hit the limit in one of our Terraform modules last week. The error message was as follows.
```
Dependabot cannot open any more pull requests
The open pull request limit has been exceeded. The current limit is: 5.
```
=> Raise limits on open PRs from Dependabot

terraform/variables/staging-intl.tfvars, terraform/variables/stg-us-facil.tfvars, terraform/variables/stg-us-pha.tfvars
While composing this I realized I accidentally bumped the version number by 11, not 1. The plans look as expected, with just container image updates.
=> Update staging to 0.6.66

.github/workflows/ci-build.yml, terraform/cluster_bootstrap/main.tf, terraform/cluster_bootstrap/modules/eks/eks.tf, terraform/main.tf, terraform/modules/eks/eks.tf
This handles the upgrade to Terraform 1.3, which is a breaking change for us as we were relying on an experiment that has now been removed. We did not use the `defaults` function at all, so we do not have to make any syntax changes to adapt to the stabilized `optional()` modifier.
We are affected by a [bug in 1.3.0 related to checks on resources inside modules](https://github.com/hashicorp/terraform/issues/31846), so I have speculatively set the minimum version to 1.3.1. This upgrade is blocked on a fix landing and being released.
=> Upgrade to Terraform 1.3

terraform/cluster_bootstrap/unused_variables.tf
This adds stub declarations for variables that are used in the main Terraform module, but not the cluster_bootstrap module. Between this and the recent Terraform 1.3 upgrade, I no longer get any warnings when planning any environment.
=> Add declarations, silence unused variable warnings

terraform/variables/prod-intl.tfvars
Per the MITRE onboarding email, the ISO code is `rw`.
This can't be deployed until the Google ingestor specific manifest is available (https://storage.googleapis.com/prio-manifests/rw-g-enpa-manifest.json) but we can get the changes approved.
=> Add data share processor for Rwanda

terraform/modules/data_share_processor/data_share_processor.tf
Putting a `lifecycle.postcondition` on a `data.http` seems to force Terraform to defer reading that resource until the apply phase. This means that any resource that depends in turn on the `data.http` can't be planned, which leaves us unable to deploy new localities.
This commit deletes the `lifecycle` blocks, which lets us `plan` and hopefully `apply` again. We should still fail obviously if some JSON manifest can't be fetched, because parsing the JSON or accessing some field of the manifest will fail.
=> Don't use postconditions on `data.http` resources

.github/workflows/push-docker-image-main.yml, .github/workflows/push-docker-image-release.yml
GitHub is now displaying a warning that [::set-output is deprecated](https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/). This updates our release publishing workflows to use the recommended replacement mechanism, "environment files".
=> GHA: Replace ::set-output with file redirection

terraform/main.tf
This is intended to induce a key rotation. Once the key rotates once, we will revert this change.
The current situation: the key versions are (`old`, `bad`). Clients are submitting reports with both `old` & `bad` key versions. The `bad` key version cannot be used by Apple due to a technical issue. We cannot immediately delete either key version as we expect to receive reports from both. Our goal is to introduce a new key version without deleting either existing key version.
Overall plan:
* Submit this PR.
* Allow the key rotator to run. Since `bad` is more than 1w old, the key rotator will introduce a new key version `new`. As `old` was generated on 1/3 (i.e. 9 months ago), and `delete_min_age` is 13 months, no key versions will be deleted.
* Revert this PR within a week of the previous …
=> Reduce creation minimum age to 1w temporarily.

terraform/main.tf
This is part of addressing the ENPA key rotation issue. See #2107 for discussion of the overall plan.
=> Restore key creation minimum age to 6480h. (attempt #2)

terraform/main.tf
Previously, we would promote a new packet encryption key to primary immediately, causing it to be advertised in our manifest as soon as it was created. Since our own jobs notice key updates on a 1h cadence, there was a small window of time where we were advertising a key that was not accepted by our jobs. We reasoned that it was very unlikely that end-user devices would receive a key update in less than one hour -- but this appears to be incorrect, based on our latest key rotation, in which a few devices appear to have started using the new key within 1h of it being introduced (leading to minor data loss).
=> Wait 23h before promoting packet encryption key to primary.

terraform/variables/staging-intl.tfvars, terraform/variables/stg-us-facil.tfvars, terraform/variables/stg-us-pha.tfvars
These plans look as expected, with just `--packet-encryption-key-primary-min-age` and container image version updates.
=> Update staging to 0.6.69

.github/workflows/ci-build.yml, facilitator/Dockerfile, facilitator/src/batch.rs, facilitator/src/gcp_oauth.rs, facilitator/src/http.rs, facilitator/src/idl.rs, facilitator/src/manifest.rs, facilitator/src/transport.rs, facilitator/src/transport/gcs.rs, facilitator/src/transport/s3.rs
This fixes and ignores various new Clippy warnings. `clippy::large_enum_variant` and `clippy::result_large_err` are ignored instead of adding boxing of the various errors.
=> Clippy fixes - Rust 1.65

.github/workflows/ci-build.yml, key-rotator/go.mod, key-rotator/key/key.go, key-rotator/storage/key_gcp.go, key-rotator/storage/key_test.go, workflow-manager/time/time.go, workflow-manager/tokenfetcher/tokenfetcher.go
This updates golangci-lint to the latest version, reformats some comments, and swaps out some deprecated items for their non-deprecated aliases.
=> Upgrade golangci-lint

.github/workflows/ci-build.yml
This switches from the unmaintained actions-rs/toolchain to dtolnay/rust-toolchain. Fixes #2160.
=> Switch to dtolnay/rust-toolchain

terraform/variables/prod-intl.tfvars
This PR enables key rotation in the prod-intl localities.
I'm staging this as a draft PR for the moment. As previously discussed, we would prefer to roll this out in coordination with the peer servers. We will need to deploy this within a week and a half to beat a certificate expiration deadline.
=> prod-intl: Enable key rotation

facilitator/Cargo.lock, facilitator/Cargo.toml, facilitator/src/bin/facilitator.rs
This registers a SIGTERM hook in each of the worker subcommands, and checks for a signal at the top of the main loop. Previously, SIGTERM signals had no effect, as the process is running as uid 0. Containers would be killed 15 seconds later with a SIGKILL. This change will make it much less likely that intake batch workers will be killed while they are processing a queue message. In turn, this means those messages won't have to wait for a timeout before being redelivered and our queues will clear out faster, preventing `intake_task_queue_growth` false alarms.
This closes #2229.
=> Gracefully exit upon SIGTERM

terraform/variables/prod-intl.tfvars
- put `key-rotator` in dry-run mode
- change packet encryption key `create_min_age` to two days
- change packet encryption key `primary_min_age` to 5 minutes
See #2248 for details
=> Re-rotate keys in `mx-yuc, mx-coa, mx-pue`, part 1

terraform/variables/prod-intl.tfvars
Change packet encryption key `delete_min_count` to 3 to avoid deleting the currently used key.
Part of #2248
=> Re-rotate keys in `mx-yuc, mx-coa, mx-pue`, part 1.5

terraform/modules/custom_metrics/custom_metrics.tf
We're migrating our EKS clusters to Kubernetes 1.22 (#2249). That release of Kubernetes promoted the `CustomResourceDefinition` resource from `apiextensions.k8s.io/v1beta1` to plain `v1`. That also changes the schema for CRDs so that they have a `versions` array instead of a single `version` ([k8s docs][1]). We update our declaration of the `kubernetes_manifest` resource to match.
[1]: https://kubernetes.io/docs/reference/kubernetes-api/extend-resources/custom-resource-definition-v1/#CustomResourceDefinitionSpec
=> terraform: update CRD specification for k8s 1.22

facilitator/src/batch.rs, facilitator/src/transport/s3.rs
This fixes some Clippy warnings in Rust 1.66.
=> Clippy fixes

terraform/modules/eks/log.tf
The [release notes](https://github.com/aws/aws-for-fluent-bit/releases/tag/v2.29.0) for this version mention that the CloudWatch plugin has been moved to a better-supported networking stack inside Fluent Bit, and that this should resolve hangs and segfaults. We've noticed SIGSEGVs shortly after CloudWatch API control plane API calls over the past few months, and this should hopefully resolve that.
=> Update to AWS for Fluent Bit 2.29.0

.github/workflows/ci-build.yml
Following up from discussion on divviup/libprio-rs#398, this caches compilation of `grcov` in CI builds. This compilation step currently takes about two and a half minutes.
=> Cache compilation of grcov

terraform/modules/monitoring/monitoring.tf, terraform/variables/prod-intl.tfvars, terraform/variables/prod-us.tfvars, terraform/variables/staging-intl.tfvars, terraform/variables/stg-us-facil.tfvars, terraform/variables/stg-us-pha.tfvars
This upgrades the `prometheus-cloudwatch-exporter` Helm chart. The most significant changes in the chart were container image version upgrades, from 0.10.0 to 0.15.0.
Most of the changes in cloudwatch-exporter itself were dependency upgrades. It also added an option to cache `ListMetrics` calls, which I enabled since this metadata changes very infrequently in our use case. (The set of values for the QueueName dimension will change when we deploy or tear down a locality) This may save us on the order of $10/month, on top of the operational benefits.
=> Bump cloudwatch-exporter, enable ListMetrics cache

terraform/Makefile
This removes `-upgrade` from our `terraform init` command lines. This will give us more predictable behavior by repeatably installing the same version of our providers. Dependabot handles provider upgrades for us, so we shouldn't have issues with falling way behind.
=> Make terraform init follow lockfile

facilitator/Cargo.toml, facilitator/src/aggregation.rs, facilitator/src/aws_credentials.rs, facilitator/src/batch.rs, facilitator/src/bin/facilitator.rs, facilitator/src/config.rs, facilitator/src/gcp_oauth.rs, facilitator/src/http.rs, facilitator/src/idl.rs, facilitator/src/logging.rs, facilitator/src/manifest.rs, facilitator/src/metrics.rs, facilitator/src/retries.rs, facilitator/src/sample.rs, facilitator/src/task.rs, facilitator/src/task/pubsub.rs, facilitator/src/task/sqs.rs, facilitator/src/transport.rs, facilitator/src/transport/gcs.rs, facilitator/src/transport/s3.rs, facilitator/tests/integration_tests.rs
This bumps the crate's edition to 2021 to make `panic!()`/`assert!()` improvements available, rewrites format strings to fix lints, and ignores more `clippy::result_large_err` lints.
=> Clippy fixes, 1.67

terraform/modules/monitoring/prometheus_alerting_rules.yml
This makes two changes to alerts which have been firing continuously since we deleted year-old keys. First, the failure rate/rejection rate alerts are all changed to sum over the aggregation ID as well. This is needed because devices having old configurations causes both uploads with expired keys and uploads to old aggregation IDs that are no longer requested. Thus, there are some aggregation IDs with 100% failure rate. Averaging over these removes the outliers, while still capturing per-locality and per-ingestor error rates.
Secondly, the thresholds for both the intake failure rate and intake rejection rate are changed to 10%. After the aggregation change, most localities have error rates in the low percents, but there are a couple with error rates at 7% or 8%. These thresholds thus have …
=> Reduce alert sensitivity for intake error rate

terraform/modules/monitoring/prometheus_alerting_rules.yml
This is a follow-up to #2413, to address further false positives from alerts. This change additionally aggregates away the `instance` and `node` labels. Due to random chance, individual pods in a deployment could process a small number of reports with more than 10% encrypted to expired keys. Summing over this label smooths out that variation. We don't need to monitor these errors on a pod-by-pod basis, since they are autoscaled.
=> Further summarize metrics for error rate alerts

facilitator/Cargo.lock, facilitator/Cargo.toml, facilitator/src/aggregation.rs, facilitator/src/bin/facilitator.rs, facilitator/src/idl.rs, facilitator/src/intake.rs, facilitator/src/sample.rs
This updates libprio-rs from 0.6.1 to 0.10.0, to get us off an unsupported version. I plan to test this in a development environment to make sure everything still works.
=> Upgrade libprio-rs to 0.10.0

terraform/main.tf
This sets `disable_on_destroy = false` for the `iamcredentials.googleapis.com` service resource in AWS-based environments. The display name of this API is "IAM Service Account Credentials API". When I destroyed my development environment, I got an error when trying to destroy this resource, because GKE and IAM were both enabled at the time, and depend on it.
Currently, `iamcredentials.googleapis.com` is explicitly enabled by `main.tf`, and implicitly enabled by `cluster_bootstrap/modules/gke/gke.tf` enabling `container.googleapis.com`. Aside from the contents of the main module, the `cluster_bootstrap` module would already leave this service enabled after destruction, because it is implicitly enabled and never explicitly disabled. This is okay, because we I don't think we get billed for …
=> Leave iamcredentials.googleapis.com when destroying AWS environment

terraform/variables/staging-intl.tfvars, terraform/variables/stg-us-pha.tfvars
AWS is deprecating EKS 1.22 in early June, but we need to continue running the international instance of ENPA through the end of that month, so we update to 1.23.
=> Updated EKS to 1.23 in staging environments

terraform/variables/staging-intl.tfvars, terraform/variables/stg-us-pha.tfvars
This updates the EBS and VPC add-ons and the cluster autoscaler to recent ones compatible with 1.23. Because we are only doing a single minor version upgrade of the VPC CNI plugin, we don't need to perform any manual updates.
=> Update EKS plugins for 1.23

terraform/modules/eks/cluster_autoscaler.tf
The 1.23 Kubernetes cluster autoscaler needs one more permission in the AWS IAM policy granted to its role to function. The current documentation ([1]) also suggests restricting some of the existing permissions to only act on specific clusters, so we do that, too.
[1]: https://docs.aws.amazon.com/eks/latest/userguide/autoscaling.html
=> Update IAM policy for EKS cluster autoscaler

terraform/variables/prod-intl.tfvars
AWS is deprecating EKS 1.22 in early June, but we need to continue running the international instance of ENPA through the end of that month, so we update to 1.23.
=> Update EKS to 1.23 in production

terraform/variables/prod-intl.tfvars
This updates the EBS and VPC add-ons and the cluster autoscaler to recent ones compatible with 1.23. Because we are only doing a single minor version upgrade of the VPC CNI plugin, we don't need to perform any manual updates.
=> Update EKS plugins for 1.23 in prod

terraform/modules/monitoring/prometheus_alerting_rules.yml
This backs out part of #2413, re-tightening some alert thresholds now that our issue with inputs encrypted to very old keys has resolved itself.
=> Increase intake error alert sensitivity

terraform/modules/monitoring/monitoring.tf, terraform/modules/nfs_server/nfs_server.tf, terraform/variables/prod-intl.tfvars, terraform/variables/staging-intl.tfvars, terraform/variables/stg-us-pha.tfvars
This switches three container images to be pulled from `registry.k8s.io` instead of `k8s.gcr.io`. The latter will be sunsetted, see https://kubernetes.io/blog/2022/11/28/registry-k8s-io-faster-cheaper-ga/. Using `registry.k8s.io` lets us fetch from a more-local backend on AWS clusters.
=> Switch to registry.k8s.io

terraform/modules/kubernetes_locality/kubernetes_locality.tf
This adds a toleration for `divviup.org/spot-vm` to the key rotation CronJob. This should hopefully help with the scheduling issues we've had over the past two days. Key rotation runs fast enough that using a spot instance should not be of concern.
=> Give key-rotator a toleration for spot VM taints

terraform/variables/prod-intl.tfvars
We are no longer deploying to prod-us because NCI's side has been torn down.
=> Deploy 0.6.95 to prod-intl

facilitator/src/transport/local.rs
This fixes a new clippy warning that appears with Rust 1.70.0.
=> Fix clippy warning
