divviup/prio-server

.github/workflows/ci-build.yml, README.md, facilitator/Cargo.lock, facilitator/Cargo.toml, facilitator/src/aggregation.rs, facilitator/src/bin/facilitator.rs, facilitator/src/idl.rs, facilitator/src/intake.rs, facilitator/src/lib.rs, facilitator/src/sample.rs, facilitator/tests/integration_tests.rs, terraform/.gitignore, terraform/Makefile, terraform/README.md, terraform/main.tf, terraform/modules/gke/gke.tf, terraform/modules/kubernetes/kubernetes.tf, terraform/variables/demo-gcp.tfvars
This commit adds a Terraform module that spins up a GKE cluster in a GCP
region, then creates one Kubernetes namespace per configured PHA and
then creates a cronjob in each namespace which just invokes `facilitator
--help` every ten minutes. Also includes a handful of README
improvements.
Addresses #15
=> terraform: module to instantiate GKE clusters

facilitator/Cargo.lock, facilitator/Cargo.toml, facilitator/src/aggregation.rs, facilitator/src/batch.rs, facilitator/src/bin/facilitator.rs, facilitator/src/idl.rs, facilitator/src/intake.rs, facilitator/src/lib.rs, facilitator/src/sample.rs, facilitator/src/test_utils.rs, facilitator/tests/integration_tests.rs
See commit messages for more info. I recommend reviewing each commit individually.
=> Use error handling libraries

facilitator/Cargo.lock, facilitator/Cargo.toml, facilitator/src/bin/facilitator.rs, facilitator/src/config.rs, facilitator/src/lib.rs, facilitator/src/transport/s3.rs
This will be useful when configuring internal paths in the workflow manager and for future file APIs.
=> Add S3Path type, add key prefix support

deploy-tool/cert/cert.go, deploy-tool/cert/kubernetes_storage.go, deploy-tool/cert/kubernetes_storage_test.go, deploy-tool/config/config.go, deploy-tool/main.go, terraform/main.tf, terraform/modules/data_share_processor/data_share_processor.tf
This edits the terraform pipeline to output the expected FQDN to be used in the deploy tool.
I've also included some style fixes for the go code in this PR.
=> Output the FQDN in Terraform output and consume it in deploy-tool

facilitator/Cargo.lock, facilitator/Cargo.toml, facilitator/src/bin/facilitator.rs, facilitator/src/bin/workflow-manager.rs, facilitator/src/config.rs, facilitator/src/idl.rs, facilitator/src/lib.rs, facilitator/src/sample.rs, facilitator/src/workflow.rs
Basically just a scaffolding with TODOs with the rough flow of the binary, to be fleshed out.
=> Add workflow manager skeleton/stubs

facilitator/README.md, facilitator/src/aggregation.rs, facilitator/src/bin/facilitator.rs, facilitator/src/intake.rs, facilitator/tests/integration_tests.rs
This pull request improves facilitator's handling of crypto key arguments, anticipating their usage by the workflow manager that will create Kubernetes jobs.
=> facilitator: improve key parameter handling

terraform/modules/kubernetes/kubernetes.tf, workflow-manager/build.sh, workflow-manager/go.mod, workflow-manager/main.go
The workflow manager can now create jobs.
Clean up the dummy code that counts pods in the cluster.
Embed some build information in workflow-manager to print at startup.
=> Workflow manager updates for Monday

.github/workflows/push-docker-image.yml
Note: I haven't tested this yet, but adapted from what was already here. Need to figure out how to test these; advice welcome!
=> Add workflow-manager publish to GitHub Actions.

facilitator/src/bin/facilitator.rs
Previously this was looking for --aggregation-identity.
=> Fix flag name for --portal-identity.

facilitator/src/bin/facilitator.rs
Also fix the name of BATCH_SIGNING_PRIVATE_KEY_IDENTIFIER
=> Add env vars for storage and manifest flags.

terraform/modules/data_share_processor/data_share_processor.tf, terraform/modules/kubernetes/kubernetes.tf
So there will always be fresh samples for the workflow-manager cron job
to consume.
=> Add a sample generator cron job.

workflow-manager/main.go
Also better handle the "already exists" error, and restore dates in job
names.
=> workflow-manager: add limits for spawned jobs.

facilitator/src/batch.rs, facilitator/src/bin/facilitator.rs, terraform/modules/data_share_processor/data_share_processor.tf, terraform/modules/kubernetes/kubernetes.tf, workflow-manager/main.go
With these changes, workflow-manager actually spawns Kubernetes jobs to run `facilitator aggregate` with suitable parameters. It doesn't yet implement the aggregation window, and I'm running into an issue with signature verification on peer validation batch signatures.
=> Start aggregation jobs in workflow-manager

terraform/modules/data_share_processor/data_share_processor.tf
For each data share processor, we create an AWS IAM role which is used
by that DSP to access various S3 buckets. We also create a bucket to
which peer DSPs will write their validation batches. We aim to grant the
entire peer AWS account access to that bucket, which we achieve with
Principal { AWS { aws-account-id } } in the _bucket_ policy. It turns
out we also need a _role_ policy permitting use of the S3 API.
Issue #140 tracks restricting this policy further.
=> terraform: Add IAM policy for bucket role

workflow-manager/main.go
Every moment in time belongs to exactly one aggregation interval, defined by the `--aggregation-period` flag. Workflow-manager will pick the interval that ended at least `--grace-period` ago, and attempt to run an aggregation job for all the batches that fall in that window.
=> Add aggregation periods to workflow-manager

facilitator/src/bin/facilitator.rs
This doesn't change any of the bodies of the subcommands, so no need to
re-review those; just took the bodies wholesale and moved them into
their own functions. One exception: The formatter unwrapped some lines
because by outdenting them, more can fit on a line.
Add `&w=1` to the review URL to ignore whitespace diffs.
=> Factor out subcommands into their own functions.

facilitator/src/bin/facilitator.rs
This fixes some issues spotted in review on #157.
=> facilitator: small fixes.

workflow-manager/main.go
This makes it easier to see recent jobs in `kubectl get pods` output.
=> workflow-manager: add date and agg ID to intake job names.

workflow-manager/Dockerfile, workflow-manager/build.sh, workflow-manager/main.go
This is the "make workflow-manager build more self-contained" PR.
=> Cherry-pick #173 into narnia

facilitator/src/bin/facilitator.rs
Mirroring workflow-manager, facilitator now accepts the empty string as
a value for its various -identity and _IDENTITY parameters, indicating
that the default credentials should be used for authentication to S3
(ambient credentials from environment) or GCS (default service account
from GKE metadata service).
=> facilitator: recognize "" as value for *_IDENTITY

deploy-tool/main.go
The deploy-tool iterates over manifests, and so was naively creating one
packet decryption key and one certificate per data share processor, but
the packet decryption keys are per-namespace, which means whichever
manifest in a namespace was constructed last, wins. This commit ensures
that deploy-tool only creates a single packet decryption key and
certificate per namespace (and hence locality).
=> deploy-tool: don't double issue packet keys

.github/workflows/push-docker-image.yml
We were missing a $ in one step.
=> GH Actions: Fix push-facilitator action

workflow-manager/main.go
Cherry picks 85aec564 / #161 into release/narnia.
=> Support multiple aggregations.

workflow-manager/main.go
=> Enable gs pagination

facilitator/src/manifest.rs
In the latest protocol iteration, data share processors advertise packet
encryption keys in PKCS#10 certificate signing requests instead of X.509
certificates issued from a publicly trusted CA. This commit teaches the
facilitator about the new specific manifest format. See #153.
=> facilitator: manifests with CSRs instead of certs

workflow-manager/main.go
Make sure that all three of ingestion batch, own validation and peer
validation are present before including a batch in an aggregation job.
Resolves #220
=> workflow-manager: check aggregation inputs

facilitator/src/bin/facilitator.rs
aggregate jobs are always provided both `own-manifest-url` and
`batch-signing-private-key`. Due to the order of arms in a match
expression, we always ignored the own-manifest, which meant we could
fail to use the right public keys to validate own validation batches.
Resolves #216
=> facilitator: prefer own manifest in aggregate

workflow-manager/main.go
workflow-manager incorrectly considered ingestion or validation batches
to be ready if any of the three files were present, causing aggregation
jobs to fail because there were missing peer validations.
Resolves #253
=> workflow-manager: ready batches bugfix

.github/workflows/ci-build.yml, workflow-manager/batchpath/batchpath.go, workflow-manager/bucket/bucket.go, workflow-manager/main.go, workflow-manager/tokenfetcher/tokenfetcher.go, workflow-manager/utils/utils.go
Doing this pre #151 to make the retry-logic code easier to write and reason about with
=> Restructure code to separate out different components

workflow-manager/errors/errors.go, workflow-manager/main.go, workflow-manager/main_test.go, workflow-manager/retry/retry.go, workflow-manager/retry/retry_test.go
=> Create retry logic

terraform/modules/data_share_processor/data_share_processor.tf, terraform/modules/kubernetes/kubernetes.tf, terraform/modules/manifest/manifest.tf
While bringing up new environments for integration testing, I encountered a couple of bugs in Terraform which this commit fixes.
=> Terraform hotfixes

terraform/variables/prod-us.tfvars
Add the `aq-aq` locality for Antarctica, and update Google's manifest
endpoint to their production value.
=> prod-us: deploy Antarctica

terraform/variables/prod-us.tfvars
Move production to use prio-facilitator and prio-workflow-manager 0.5.1.
=> terraform: pin prod-us to 0.5.1

workflow-manager/bucket/bucket.go
Performance increase per:
https://pkg.go.dev/cloud.google.com/go/storage#Query.SetAttrSelection
=> Set attr selection to name as we don't care about the other object attributes

facilitator/src/task/sqs.rs
NCI observed a problem where acknowledging tasks in SQS was failing
because the connection pool underneath Rusoto was closing idle
connections, leading to a race condition when trying to reuse an
SqsClient. The simple fix is to create a new SqsClient for each request
to the SQS API.
=> facilitator: use a new SqsClient for each request

facilitator/Cargo.lock, facilitator/Cargo.toml, facilitator/src/config.rs, facilitator/src/gcp_oauth.rs, facilitator/src/http.rs, facilitator/src/manifest.rs, facilitator/src/task/pubsub.rs, facilitator/src/transport/gcs.rs, facilitator/src/transport/s3.rs
Upgrade to ureq2
- Addresses #297
- Will address #296 in the future
=> Explore upgrading to ureq 2

workflow-manager/limiter/limiter_test.go
Fixes #346 
It looks like the t.Log() calls in the goroutines are sometimes (read=rarely) called after the main goroutine for the test has finished executing. This ends up causing a panic in the internal tester framework, which ended up in randomly uncovering this bug in #346.
There is possibly a way to fix this without the waitgroup, but the waitgroup does make it much easier to reason about.
=> Fixes data race uncovered by a test run

facilitator/Cargo.lock, facilitator/Cargo.toml, facilitator/src/config.rs, facilitator/src/gcp_oauth.rs, facilitator/src/http.rs, facilitator/src/manifest.rs, facilitator/src/task/pubsub.rs, facilitator/src/transport/gcs.rs, facilitator/src/transport/s3.rs
Reverts abetterinternet/prio-server#330
=> Revert "Explore upgrading to ureq 2"

.github/workflows/push-docker-image-main.yml
Made a copy-paste mistake with #380, this fixes it.
=> Automatically publish main-latest for workflow manager

facilitator/src/bin/facilitator.rs, facilitator/src/lib.rs, facilitator/src/logging.rs
This is step one in the progress for better logging. Let's get the severity values right and then we can look into adding more fields to search by to the payload.
=> Better logging for faciltiator

terraform/modules/data_share_processor/data_share_processor.tf
`ENV=prod-us make plan` was failing because the g-enpa ingestor
manifests do not have `server-identity.aws-iam-entity`. This commit
refactors the handling of `server-identity.aws-iam-entity` and
`server-identity.gcp-service-account-email` so that they are only
consulted when necessary.
=> terraform: aws-iam-entity is optional in manifest

terraform/variables/staging-facil.tfvars, terraform/variables/staging-pha.tfvars
Pins workflow manager and facilitator to 0.6.10 for a deployment to the staging environment.
=> Pin worflow manager and facilitator to 0.6.10

terraform/variables/prod-us.tfvars
- adds `us-ma` locality
- increases size of intake-batch worker pool for `us-wi-apple`
=> 2021-03-16 production deployment

workflow-manager/.gitignore
adds a .gitignore for `workflow-manager`
=> workflow-manager: .gitignore

facilitator/README.md, workflow-manager/README.md
=> Document that SQS raw message delivery is required

terraform/variables/prod-us.tfvars
Configures data share processors for the District of Columbia.
=> terraform: configure us-dc region

facilitator/src/bin/facilitator.rs, facilitator/src/config.rs
PR #728 added support for GCP Workload Identity Pool to federate
identity from AWS to GCP. It added a
`gcp-workload-identity-pool-provider` command line argument, but failed
to wire it up to the various `facilitator` subcommands that need it.
Besides that, we need allow Terraform to pass
`GCP_WORKLOAD_IDENTITY_POOL_PROVIDER = ""` when running `facilitator`
(it's easier to handle this in Rust than to conditionally add values to
Terraform maps), so we add a `WorkloadIdentityPoolParameters::new`
function that looks for the empty string and treats it as equivalent to
the argument not having been specified.
=> facilitator: fix GCP workload identity pool args

facilitator/src/bin/facilitator.rs, facilitator/src/manifest.rs
This PR adds support for new manifest formats needed to support #747
=> `facilitator`: support new manifest formats

terraform/variables/staging-intl.tfvars
Adds a .tfvars file for the `staging-intl` environment, which we use for
integration testing with our international partners.
Part of #659
=> terraform: add staging-intl vars file

terraform/modules/monitoring/monitoring.tf
Some fixes for EBS-backed persistent storage for prometheus-server in
EKS clusters:
- conditionally check available GCP or AWS zones based on what we're
deploying to, so that we don't have to activate the GCP compute API
when deploying to EKS
- configure a `node_affinity` on the EBS `kubernetes_persistent_volume`
to ensure that `prometheus-server` gets scheduled onto a node in the
same AZ as the EBS volume
=> terraform: metrics storage in EBS for EKS clusters

deploy-operator/controllers/locality_controller.go, workflow-manager/storage/storage_test.go
Only two files needed changes.
=> run gofmt -s on the codebase

.github/workflows/ci-build.yml, key-rotator/go.mod, key-rotator/go.sum, key-rotator/key/key.go, key-rotator/key/key_test.go
I'm happy with most of this. The one thing I may consider changing as I move forward with implementation is the RotationConfig.CreateKeyFunc; I may factor this out to something like a "key profile" (name not final) that knows how to generate new keys, serialize them for the various places they need to be written, etc -- the idea being I'd have one key profile for batch signing keys & one key profile for packet encryption keys.
=> key rotator: implement basic Key data type & rotation logic.

key-rotator/.gitignore, key-rotator/go.mod, key-rotator/go.sum, key-rotator/key/key.go, key-rotator/key/key_test.go, key-rotator/main.go, key-rotator/main_test.go, key-rotator/manifest/manifest.go, key-rotator/manifest/manifest_test.go, key-rotator/storage/test/key.go, key-rotator/storage/test/manifest.go
Other than unit tests, I ran this against my dev environment in dry run mode & the results look reasonable.
There are a number of tasks before we are ready to deploy this in production & start rotating keys:
* A number of validations need to be added (tracked in https://github.com/abetterinternet/prio-server/issues/24 -- some of these are implemented in tests already, but they need to be added to the main program logic)
* Metrics/alerting
* Automated key backup
=> Key rotator binary

.github/workflows/ci-build.yml, .github/workflows/push-docker-image-main.yml, .github/workflows/push-docker-image-release.yml
This fixes some issues with Docker image CI actions that I noticed while catching up on recent changes. See the commit messages for details.
=> Docker CI fixes

facilitator/src/manifest.rs
I noticed this in
https://github.com/abetterinternet/prio-server/runs/4359804801?check_suite_focus=true:
`clippy` was complaining because one of the errors included a format
verb, but no formatting argument was provided.
I fix this by dropping the problematic format arg entirely, instead
factoring the key identifier out to error context at point-of-call to
the affected function.
(I also took the chance to add a little context to the error messages generated by `public_key_from_pem`, but this is of marginal value -- feel free to push back & I'll drop this part of the PR.)
=> Fix Clippy complaint about mismatched format args.

key-rotator/key/material.go, key-rotator/key/material_test.go
While caught in dev, the bug that led to https://github.com/abetterinternet/prio-server/commit/8de3dd6482170ad7a843e3028433154dc40323d8 was scary:
it caused us to write keys whose private key did not correspond to the
public key. The key-rotator didn't catch this because it was trying to
treat keys as basically an opaque value that can be parsed/serialized
in various ways, as opposed to a key that can be used for various
cryptographic operations.
Add validations to P-256 values created from any source. Some of the
checks are currently redundant (e.g. the `UnmarshalBinary` path will
currently check if the public key corresponds to a point on the curve
twice), but I leave potential performance enhancements for the future.
=> Key rotator: add sanity checks to parsed keys.

terraform/variables/prod-intl.tfvars
Re-deploy Mongolia with correct ISO code for nationwide deployment.
Resolves #1080
=> prod-intl: replace `mn-mn` with `mn`

facilitator/Cargo.lock, facilitator/Cargo.toml, facilitator/src/aggregation.rs, facilitator/src/aws_credentials.rs, facilitator/src/bin/facilitator.rs, facilitator/src/config.rs, facilitator/src/gcp_oauth.rs, facilitator/src/http.rs, facilitator/src/intake.rs, facilitator/src/manifest.rs, facilitator/src/metrics.rs, facilitator/src/task/pubsub.rs, facilitator/src/task/sqs.rs, facilitator/src/transport/gcs.rs, facilitator/src/transport/s3.rs
This change adds a whole bunch of new metrics, described in individual commit messages.
=> `facilitator`: new metrics

key-rotator/main.go, terraform/main.tf, terraform/modules/kubernetes_locality/kubernetes_locality.tf
AWS deployments will back up to AWS, GCP deployments will back up to GCP.
Currently, we always back up to the same AWS account / GCP project as the "main" Kubernetes deployment. I think this is sufficient for a first pass at backup: the Key Rotator only has permissions to write secrets (i.e. it can't delete existing secret versions), no other automation has any permissions on the AWS/GCP Secrets Manager. A human operator could e.g. delete the entire project, but at that level of error, they could just as easily delete the "separate" backup project as well.
=> Configure Key Rotator to back up secrets to AWS/GCP secret store.

terraform/variables/prod-intl.tfvars, terraform/variables/staging-intl.tfvars
`staging-intl` is already pushed & looks good, will push `prod-intl` once this is approved.
=> Release {staging,prod}-intl to 0.6.22.

terraform/cluster_bootstrap/modules/gke/gke.tf
Reverts abetterinternet/prio-server#1316
=> Revert "terraform: opt into spot VMs on GKE"

facilitator/src/bin/facilitator.rs
This makes two neighboring changes to `main()`. First, I pulled out construction of the `clap::App` into a separate function. This will be the first step of migrating to the next major version of `clap`, but meanwhile, it's convenient to be able to fold it. Second, I noticed that when certain jobs bail on a fatal 404 error, they panic on the way out because the global logger gets torn down before a `ureq::Stream` gets dropped, and attempts to log. I fixed this by splitting `main()` into two functions and reporting errors before the outer one returns. (You can see this behavior by running `facilitator validate-ingestion-sample-worker` with `--pha-manifest-base-url=https://httpbin.org/status/404`)
=> Facilitator: main function refactor

terraform/variables/prod-intl.tfvars, terraform/variables/prod-us.tfvars, terraform/variables/staging-intl.tfvars, terraform/variables/stg-us-facil.tfvars, terraform/variables/stg-us-pha.tfvars
I plan to push to staging immediately once the release is cut, and production on Thursday.
=> Release 0.6.26.

terraform/variables/staging-intl.tfvars, terraform/variables/stg-us-facil.tfvars, terraform/variables/stg-us-pha.tfvars
I have reviewed the plans for the three staging environments, and they look good. I plan to apply these tomorrow morning.
=> Deploy 0.6.27 to staging

terraform/variables/prod-intl.tfvars, terraform/variables/prod-us.tfvars
=> Deploy 0.6.28 prod

terraform/cluster_bootstrap/main.tf, terraform/main.tf, terraform/modules/kubernetes/kubernetes.tf, terraform/modules/monitoring/monitoring.tf
This will mean more Dependabot PRs, but it prevents automatically updating while running make. (See also #1469)
=> Pin Terraform provider versions

terraform/variables/staging-intl.tfvars, terraform/variables/stg-us-facil.tfvars, terraform/variables/stg-us-pha.tfvars
There are no changes in the cluster_bootstrap phase plans, and only container version changes in the main phase plans.
=> Deploy 0.6.30 to staging

terraform/variables/staging-intl.tfvars, terraform/variables/stg-us-facil.tfvars, terraform/variables/stg-us-pha.tfvars
Spot-checking stg-us-facil, all updates are to container versions.
=> Update staging to 0.6.32.

terraform/variables/prod-intl.tfvars, terraform/variables/prod-us.tfvars
Spot-checking prod-us, all updates are to container versions.
=> Update prod to 0.6.32.

terraform/variables/staging-intl.tfvars, terraform/variables/stg-us-facil.tfvars, terraform/variables/stg-us-pha.tfvars
The plans all consist of image version updates, Prometheus alerting rules, and Grafana dashboards, as expected.
=> Update staging to 0.6.33

terraform/variables/prod-intl.tfvars, terraform/variables/prod-us.tfvars
The plans for this look good, just image version updates. Staging is humming along fine.
=> Update production to 0.6.33

facilitator/src/http.rs
This should make us more resilient to connection close errors when fetching manifests.
=> Make simple_get_request retry errors in body

terraform/variables/staging-intl.tfvars, terraform/variables/stg-us-facil.tfvars, terraform/variables/stg-us-pha.tfvars
The plans look good, they just include container image updates and the new dashboard file.
=> Update staging to 0.6.36

terraform/variables/prod-intl.tfvars, terraform/variables/prod-us.tfvars
The plans for this look good, it's just container image updates.
=> Update production to 0.6.36

terraform/modules/custom_metrics/custom_metrics.tf
This includes Kubernetes 1.22 compatibility fixes.
=> Upgrade custom-metrics-stackdriver-adapter

terraform/variables/staging-intl.tfvars, terraform/variables/stg-us-facil.tfvars, terraform/variables/stg-us-pha.tfvars
The plans look as expected, with no changes to the cluster_bootstrap phase, and only container image updates in the main phase.
=> Update staging to 0.6.41

terraform/modules/kubernetes/kubernetes.tf
While monitoring our Kubernetes clusters, I noticed that some workflow-manager pods were stuck in `Pending` for a few minutes due to CPU resource constraints. (They did schedule successfully a few minutes later, once the stampede of CronJobs firing had cleared out) I saw `NotTriggerScaleUp` and `FailedScheduling` events.
To address this, these changes put a toleration for the spot VM taint on workflow-manager. This will give these pods more nodes that they can schedule on, and give cluster-auto-scaler a means to respond to the workload, since the spot node pools aren't capped at one per zone.
The downside is that workflow-manager may be running on a spot node when it is terminated, but this should be acceptable because the job will likely complete within the grace period before …
=> Give workflow-manager a toleration for spot VMs

facilitator/src/gcp_oauth.rs
We observed a pod crash and reboot three times because it was getting a 404 from `metadata.google.internal`. (presumably prior to issuing its first Pub/Sub request) This PR reconfigures our HTTP client to retry upon receiving a 404 status code for such requests.
=> Retry 404 status codes from GCE metadata server

terraform/modules/monitoring/monitoring.tf
This rewrites the template for VictorOps's "state message" field to provide more information. The key improvements are:
- A summary is always displayed, even if the summary varies due to differing labels.
- A description annotation is displayed, similar to the summary. (Previously, these descriptions we wrote were not surfaced in VictorOps)
- All labels are displayed, with common labels and distinct labels split up. (Only having `.CommonLabels` has made it hard to tell what's going on)
- A new ConfigMap is introduced to break out template blocks.
Here's a sample of the template output.
```
Summary: Container is in a restart loop.
Description: Container facile-container is restarting repeatedly in pod crasher-1-ingestor-1-786df85486-hz9qm, namespace narnia, and environment dcook-pha. (and …
```
=> Rewrite VictorOps message templates

workflow-manager/main.go
This adds fields with aggregation IDs and aggregation intervals to more logging messages. This will make it easier filter logs while diagnosing aggregation issues. Previously, some messages could only be tied to a given aggregation by their temporal relationship to other messages that did include the aggregation ID.
=> workflow-manager: Add more fields to log messages

terraform/variables/staging-intl.tfvars, terraform/variables/stg-us-pha.tfvars
=> update EKS plugin versions in staging

terraform/variables/prod-intl.tfvars, terraform/variables/staging-intl.tfvars, terraform/variables/stg-us-pha.tfvars
=> update EKS plugin versions in production

terraform/modules/monitoring/monitoring.tf
This updates the container images we use for various Prometheus components. I gave this a quick try on my dev environment, and everything looks fine.
=> Update Prometheus component container images
